function applySettings(){const s=getSettings();const html=document.documentElement;html.dataset.theme=s.theme;html.dataset.accent=s.accent;html.dataset.iconSize=s.iconSize;html.dataset.iconWeight=s.iconWeight;html.dataset.fontFamily=s.fontFamily;html.dataset.hideTabLabels=String(Boolean(s.hideTabLabels));html.style.setProperty('--base-font-weight',s.fontWeight);document.getElementById('topVersion')?.classList.toggle('hidden',!s.showVersion);document.getElementById('showVersionToggle')?.setAttribute('aria-checked',String(Boolean(s.showVersion)));document.getElementById('hideTabLabelsToggle')?.setAttribute('aria-checked',String(Boolean(s.hideTabLabels)));updateSegmentIndicator(document.getElementById('themeControl'),'themeValue',s.theme);updateSegmentIndicator(document.getElementById('iconSizeControl'),'iconSize',s.iconSize);updateSegmentIndicator(document.getElementById('iconWeightControl'),'iconWeight',s.iconWeight);updateSegmentIndicator(document.getElementById('fontFamilyControl'),'fontFamily',s.fontFamily);updateSegmentIndicator(document.getElementById('fontWeightControl'),'fontWeight',s.fontWeight);updateSegmentIndicator(document.getElementById('healthImportModeControl'),'healthMode',s.healthImportMode);document.querySelectorAll('[data-accent]').forEach(b=>b.classList.toggle('selected',b.dataset.accent===s.accent));hydrateIcons();updateTabBubble()}

function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,2);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(EVENTS)){const s=d.createObjectStore(EVENTS,{keyPath:'id'});s.createIndex('timestamp','timestamp');s.createIndex('type','type')}if(!d.objectStoreNames.contains(AUDIO))d.createObjectStore(AUDIO,{keyPath:'id'});if(!d.objectStoreNames.contains(MEDICATIONS))d.createObjectStore(MEDICATIONS,{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function store(name=EVENTS,mode='readonly'){return db.transaction(name,mode).objectStore(name)}
function req(r){return new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function allEvents(){return req(store(EVENTS).getAll())}
async function putEvent(e){return req(store(EVENTS,'readwrite').put(e))}
async function deleteEvent(id){await req(store(EVENTS,'readwrite').delete(id));await req(store(AUDIO,'readwrite').delete(id))}
async function saveAudio(id,blob){return req(store(AUDIO,'readwrite').put({id,blob}))}
async function getAudio(id){return req(store(AUDIO).get(id))}
async function allMedications(){return req(store(MEDICATIONS).getAll())}
async function putMedication(m){m.updatedAt=new Date().toISOString();return req(store(MEDICATIONS,'readwrite').put(m))}
async function deleteMedication(id){return req(store(MEDICATIONS,'readwrite').delete(id))}

const demoEvents=()=>{const now=new Date(),today=(h,m)=>{const d=new Date(now);d.setHours(h,m,0,0);return d.toISOString()},yday=(h,m)=>{const d=new Date(now);d.setDate(d.getDate()-1);d.setHours(h,m,0,0);return d.toISOString()};return[{id:'demo-note-1',type:'note',timestamp:today(21,14),text:'Estou mais tranquilo agora.',tag:'calma',demo:true},{id:'demo-med-1',type:'medication',timestamp:today(18,32),medication:'Paroxetina',dose:'20 mg',totalDoseValue:20,doseUnit:'mg',unitsTaken:1,demo:true},{id:'demo-note-2',type:'note',timestamp:today(15,10),text:'Estava bastante ansioso durante a tarde e com dor de cabeça.',tag:'ansiedade',demo:true},{id:'demo-med-2',type:'medication',timestamp:today(9,3),medication:'Bupropiona',dose:'150 mg',totalDoseValue:150,doseUnit:'mg',unitsTaken:1,demo:true},{id:'demo-sleep-1',type:'sleep',timestamp:today(7,20),startTime:yday(23,50),endTime:today(7,20),quality:4,note:'Acordei uma vez durante a madrugada.',source:'manual',demo:true},{id:'demo-buy-1',type:'purchase',timestamp:yday(17,20),medication:'Paroxetina 20 mg',packages:1,totalUnits:30,price:'R$ 41,90',place:'Farmácia de exemplo',demo:true}]}
async function seedDemo(){const e=await allEvents();if(!e.length&&localStorage.getItem('registro-demo-seeded')!=='yes'){for(const item of demoEvents())await putEvent(item);localStorage.setItem('registro-demo-seeded','yes')}}
async function ensureProfiles(){const meds=await allMedications();if(meds.length)return;const events=await allEvents(),names=[...new Set(events.filter(e=>e.type==='medication'&&e.medication).map(e=>e.medication.trim()))];for(const name of names){const doses=[...new Set(events.filter(e=>e.type==='medication'&&normalizeText(e.medication)===normalizeText(name)&&e.dose).map(e=>e.dose))];const presentations=doses.map(d=>{const p=parseStrength(d);return{id:uid('presentation'),strengthValue:p?.value||'',strengthUnit:p?.unit||'mg',form:'comprimido/cápsula',unitsPerPackage:'',unitsPerBlister:'',brand:'',lab:''}});await putMedication({id:uid('med'),activeIngredient:name,referenceName:'',lab:'',presentations,notes:[],createdAt:new Date().toISOString()})}}

function medicationDisplay(m){return m.referenceName?`${m.activeIngredient} · ${m.referenceName}`:m.activeIngredient}
function presentationDisplay(p){const strength=p.strengthValue?`${p.strengthValue} ${p.strengthUnit||''}`.trim():'Sem dosagem';const extra=[p.brand,p.lab].filter(Boolean).join(' · ');return extra?`${strength} · ${extra}`:strength}
function findProfileByEvent(e,meds){if(e.medicationId)return meds.find(m=>m.id===e.medicationId)||null;const key=normalizeText(e.medication||'');return meds.find(m=>[m.activeIngredient,m.referenceName,...(m.aliases||[])].some(v=>v&&normalizeText(v)===key))||null}
function findPresentation(m,id){return m?.presentations?.find(p=>p.id===id)||null}
function medSearchScore(m,q){q=normalizeText(q);if(!q)return 999;const candidates=[m.activeIngredient,m.referenceName,m.lab,...(m.aliases||[])].filter(Boolean).map(normalizeText);let best=999;for(const c of candidates){if(c.startsWith(q))best=Math.min(best,0);else if(c.includes(q))best=Math.min(best,1);else{const d=levenshtein(c,q);if(d<=2)best=Math.min(best,2+d/10);const first=c.split(' ')[0];const qfirst=q.split(' ')[0];const fd=levenshtein(first,qfirst);if(fd<=2)best=Math.min(best,3+fd/10)}}return best}
function medMatchesEvent(m,e){if(e.medicationId===m.id)return true;const q=normalizeText(e.medication||'');return [m.activeIngredient,m.referenceName,...(m.aliases||[])].filter(Boolean).some(v=>normalizeText(v)===q)}

function kindInfo(e){if(e.type==='note')return{kind:e.audioOnly?'ANOTAÇÃO DE VOZ':'ANOTAÇÃO',className:'note',title:e.text||'Gravação de voz',meta:[e.tag].filter(Boolean)};if(e.type==='medication')return{kind:'MEDICAMENTO',className:'medication',title:`${e.medication||'Medicamento'}${e.dose?` · ${e.dose}`:''}`,meta:[e.unitsTaken?`${e.unitsTaken} un.`:e.quantity,e.note].filter(Boolean)};if(e.type==='sleep')return{kind:'SONO',className:'sleep',title:durationLabel(durationHours(e.startTime,e.endTime)),meta:[e.quality?`Qualidade ${e.quality}`:null,e.source==='health-shortcut'?'Importado do Saúde':'Manual',e.note].filter(Boolean)};return{kind:'COMPRA',className:'purchase',title:`${e.medication||'Medicamento'}${e.price?` · ${e.price}`:''}`,meta:[e.packages?`${e.packages} caixa(s)`:e.quantity,e.place].filter(Boolean)}}
function eventCard(e){const k=kindInfo(e);return`<article class="timeline-item"><div class="timeline-time">${timeLabel(e.timestamp)}</div><div><div class="timeline-kind kind-${k.className}">${k.kind}</div><div class="timeline-title">${esc(k.title)}</div>${k.meta.length?`<div class="timeline-meta">${k.meta.map(esc).join(' · ')}</div>`:''}${e.hasAudio?`<div data-audio="${e.id}"></div>`:''}</div><button class="item-menu" data-menu="${e.id}" aria-label="Opções">•••</button></article>`}
async function hydrateAudio(root){for(const el of root.querySelectorAll('[data-audio]')){const rec=await getAudio(el.dataset.audio);if(rec?.blob){const url=URL.createObjectURL(rec.blob);el.innerHTML=`<audio controls preload="metadata" src="${url}"></audio>`}}}
function summaryRow(icon,label,valueHtml){return`<div class="summary-row"><span class="summary-row-icon">${svg(icon)}</span><span class="summary-row-label">${label}</span><span class="summary-row-value">${valueHtml}</span></div>`}
