async function wireMedicationAutocomplete(inputId,onSelect){const input=document.getElementById(inputId),box=document.getElementById('medAutocomplete');if(!input||!box)return;const render=async()=>{const q=input.value.trim();if(!q){box.classList.add('hidden');return}const list=await medicationSuggestions(q);box.innerHTML=list.map(m=>`<button type="button" data-med-choice="${m.id}"><strong>${esc(medicationDisplay(m))}</strong><small>${esc((m.presentations||[]).map(p=>presentationDisplay(p)).slice(0,3).join(' · ')||'Sem apresentação cadastrada')}</small></button>`).join('');box.classList.toggle('hidden',!list.length);box.querySelectorAll('[data-med-choice]').forEach(b=>b.onclick=async()=>{const meds=await allMedications(),m=meds.find(x=>x.id===b.dataset.medChoice);if(!m)return;input.value=medicationDisplay(m);box.classList.add('hidden');onSelect?.(m)})};input.addEventListener('input',render);input.addEventListener('focus',render)}

async function openNoteSheet(){currentType='note';pendingAudio=null;const now=toLocalInput();openBackdrop('Nova anotação',`<div class="field"><label for="noteText">Anotação</label><textarea id="noteText" placeholder="O que você percebeu, sentiu ou pensou?"></textarea></div><div class="voice-row"><button type="button" class="voice-button" id="voiceBtn">🎙 Gravar voz</button><span class="voice-status" id="voiceStatus">Opcional. O áudio fica neste aparelho.</span></div><div class="field"><label for="noteTag">Tag opcional</label><input id="noteTag" placeholder="Ex.: ansiedade, calma, sono"></div>${dateField('recordTime','Data e horário',now,{showNow:true,reserveNow:true})}<p class="helper">“agora” desaparece se você alterar a data ou o horário.</p>${formButtons()}`,saveForm);currentType='note';setupVoice()}

function presentationOptions(m){return`<option value="">Sem apresentação específica</option>${(m?.presentations||[]).map(p=>`<option value="${p.id}">${esc(presentationDisplay(p))}</option>`).join('')}`}
async function openMedicationSheet(){currentType='medication';pendingAudio=null;selectedMedicationId=null;selectedPresentationId=null;const now=toLocalInput(),suggest=await typicalMedicationSuggestion();openBackdrop('Registrar medicamento',`${suggest?`<button type="button" class="med-suggestion-card" id="timeMedSuggestion" data-med-id="${suggest.m.id}"><span class="mini-icon">${svg('clock')}</span><span><strong>Talvez agora: ${esc(suggest.m.activeIngredient)}</strong><small>Baseado nos horários das suas administrações registradas</small></span><span class="chev">›</span></button>`:''}<div class="field autocomplete"><label for="medName">Medicamento</label><input id="medName" placeholder="Comece a digitar…" autocomplete="off">${autocompleteHTML()}</div><div class="field hidden" id="presentationField"><label for="presentationSelect">Apresentação</label><select id="presentationSelect"></select></div><div class="field"><label>Como quer informar a dose?</label><div class="segmented animated-segmented" id="doseMode"><button type="button" data-dose-mode="total">Dose total</button><button type="button" data-dose-mode="perUnit">Por comprimido/cápsula</button></div></div><div id="doseFields"></div><div class="field"><label for="medNote">Observação opcional</label><input id="medNote" placeholder="Ex.: após comer"></div>${dateField('recordTime','Data e horário',now,{showNow:true,reserveNow:true})}${formButtons()}`,saveForm);currentType='medication';let mode='perUnit';const setMode=async m=>{mode=m;updateSegmentIndicator(document.getElementById('doseMode'),'doseMode',mode);await renderDoseFields(mode)};document.querySelectorAll('[data-dose-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.doseMode));await setMode('perUnit');const selectMed=async m=>{selectedMedicationId=m.id;document.getElementById('presentationField').classList.remove('hidden');const sel=document.getElementById('presentationSelect');sel.innerHTML=presentationOptions(m);if((m.presentations||[]).length===1){sel.value=m.presentations[0].id;selectedPresentationId=sel.value}sel.onchange=async()=>{selectedPresentationId=sel.value||null;await renderDoseFields(mode)};await renderDoseFields(mode)};await wireMedicationAutocomplete('medName',selectMed);document.getElementById('timeMedSuggestion')?.addEventListener('click',async e=>{const meds=await allMedications(),m=meds.find(x=>x.id===e.currentTarget.dataset.medId);if(m){document.getElementById('medName').value=medicationDisplay(m);await selectMed(m)}})}
async function renderDoseFields(mode){
  const box=document.getElementById('doseFields');
  if(!box)return;
  const meds=await allMedications();
  const m=meds.find(x=>x.id===selectedMedicationId);
  const p=findPresentation(m,selectedPresentationId);
  if(mode==='total'){
    box.innerHTML=`<div class="field"><label>Dose total tomada</label><div class="inline-unit"><input id="totalDoseValue" inputmode="decimal" placeholder="Ex.: 70"><select id="doseUnit"><option>mg</option><option>mcg</option><option>g</option><option>mL</option></select></div></div>`;
  }else{
    box.innerHTML=`<div class="field-grid"><div class="field"><label>Dose de cada unidade</label><input id="unitDoseValue" inputmode="decimal" value="${esc(p?.strengthValue||'')}" placeholder="70"></div><div class="field"><label>Quantidade</label><input id="unitsTaken" inputmode="decimal" value="1"></div></div><div class="field"><label>Unidade</label><select id="doseUnit"><option ${p?.strengthUnit==='mg'?'selected':''}>mg</option><option ${p?.strengthUnit==='mcg'?'selected':''}>mcg</option><option ${p?.strengthUnit==='g'?'selected':''}>g</option><option ${p?.strengthUnit==='mL'?'selected':''}>mL</option></select></div><div class="dose-result"><span>Dose total calculada</span><strong id="doseTotalPreview">—</strong></div>`;
    const update=()=>{
      const v=Number(String(document.getElementById('unitDoseValue').value).replace(',','.'));
      const q=Number(String(document.getElementById('unitsTaken').value).replace(',','.'))||1;
      const u=document.getElementById('doseUnit').value;
      document.getElementById('doseTotalPreview').textContent=Number.isFinite(v)?`${(v*q).toLocaleString('pt-BR')} ${u}`:'—';
      document.getElementById('unitsTaken').value=document.getElementById('unitsTaken').value||'1';
    };
    ['unitDoseValue','unitsTaken','doseUnit'].forEach(id=>document.getElementById(id)?.addEventListener('input',update));
    update();
  }
  hydrateIcons(box);
}

async function openPurchaseSheet(){currentType='purchase';selectedMedicationId=null;selectedPresentationId=null;const now=toLocalInput();openBackdrop('Registrar compra',`<div class="field autocomplete"><label for="purchaseMed">Medicamento</label><input id="purchaseMed" placeholder="Comece a digitar…" autocomplete="off">${autocompleteHTML()}</div><div class="field hidden" id="purchasePresentationField"><label for="purchasePresentation">Apresentação</label><select id="purchasePresentation"></select></div><div class="field-grid"><div class="field"><label for="purchasePackages">Caixas</label><input id="purchasePackages" inputmode="numeric" value="1"></div><div class="field"><label for="purchasePrice">Valor total pago</label><input id="purchasePrice" inputmode="decimal" placeholder="R$ 42,90"></div></div><div class="field"><label for="purchasePlace">Onde comprou</label><input id="purchasePlace" placeholder="Farmácia ou loja"></div><div class="analysis-row hidden" id="purchaseCostPreview"><strong>Custos calculados</strong><span id="purchaseCostText"></span></div>${dateField('recordTime','Data e horário',now,{showNow:true,reserveNow:true})}${formButtons()}`,saveForm);currentType='purchase';const onSelect=async m=>{selectedMedicationId=m.id;const field=document.getElementById('purchasePresentationField'),sel=document.getElementById('purchasePresentation');field.classList.remove('hidden');sel.innerHTML=presentationOptions(m);if((m.presentations||[]).length===1){sel.value=m.presentations[0].id;selectedPresentationId=sel.value}sel.onchange=()=>{selectedPresentationId=sel.value||null;updatePurchasePreview()};updatePurchasePreview()};await wireMedicationAutocomplete('purchaseMed',onSelect);['purchasePackages','purchasePrice'].forEach(id=>document.getElementById(id)?.addEventListener('input',updatePurchasePreview))}
