/* Entrevista pessoal do motor + prévias compactas no Histórico. */
const PERSONAL_INTERVIEW_VERSION='1.0.1';
const PERSONAL_INTERVIEW_GAP_DAYS=15;
const PERSONAL_INTERVIEW_REASONS=[
  ['forgot','Esqueci de anotar'],
  ['discouraged','Estava desanimado'],
  ['sad','Estava triste'],
  ['happy_busy','Estava feliz e envolvido com outras coisas'],
  ['busy','Estava muito ocupado'],
  ['tired','Estava cansado / sem energia'],
  ['distracted','Estava distraído / desatento'],
  ['dont_know','Não sei / não lembro']
];

function personalInterviewState(){const s=getSettings();return{responses:{...(s.personalInterview?.responses||{})},dismissed:{...(s.personalInterview?.dismissed||{})}}}
function personalInterviewSave(state){const s=getSettings();s.personalInterview={version:1,responses:state.responses,dismissed:state.dismissed};saveSettings(s)}
function personalInterviewDate(v){return new Date(v).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric'})}
function personalInterviewStartKey(timestamp){return String(new Date(timestamp).getTime())}

async function personalInterviewTextEvents(events,meds){const narratives=typeof continuityNarratives==='function'?await continuityNarratives(events,meds):await learningCollectObservations(events,meds);return narratives.filter(o=>String(o.text||'').trim()).sort((a,b)=>new Date(a.timestamp)-new Date(b.timestamp))}
async function personalInterviewQuestions(events,meds){const texts=await personalInterviewTextEvents(events,meds),state=personalInterviewState(),answeredStarts=new Set(Object.values(state.responses).map(r=>r.startKey).filter(Boolean)),dismissedStarts=new Set(Object.values(state.dismissed).map(r=>r.startKey).filter(Boolean)),questions=[];
  for(let i=1;i<texts.length;i++){
    const before=texts[i-1],after=texts[i],gap=(new Date(after.timestamp)-new Date(before.timestamp))/86400000,startKey=personalInterviewStartKey(before.timestamp);if(gap<PERSONAL_INTERVIEW_GAP_DAYS||answeredStarts.has(startKey)||dismissedStarts.has(startKey))continue;const key=`text-gap|${startKey}|${new Date(after.timestamp).getTime()}`;questions.push({key,startKey,gap,before,after,open:false})
  }
  if(texts.length){const before=texts[texts.length-1],gap=(Date.now()-new Date(before.timestamp).getTime())/86400000,startKey=personalInterviewStartKey(before.timestamp);if(gap>=PERSONAL_INTERVIEW_GAP_DAYS&&!answeredStarts.has(startKey)&&!dismissedStarts.has(startKey))questions.push({key:`text-gap|${startKey}|open`,startKey,gap,before,after:null,open:true})}
  return questions.sort((a,b)=>b.gap-a.gap).slice(0,4)
}
function personalInterviewQuestionHTML(q){const period=q.open?`Você está há ${Math.floor(q.gap)} dias sem registrar um texto ou observação.`:`Houve um intervalo de ${q.gap.toFixed(1).replace('.',',')} dias entre ${personalInterviewDate(q.before.timestamp)} e ${personalInterviewDate(q.after.timestamp)}.`;return`<article class="learning-question personal-interview-question" data-interview-question="${esc(q.key)}"><span class="learning-confidence medium">ENTREVISTA PESSOAL</span><h3>${esc(period)}</h3><p>Gostaria de informar se houve algum motivo? Sua resposta vira contexto relatado por você; o app não presume o motivo sozinho.</p><div class="interview-reasons">${PERSONAL_INTERVIEW_REASONS.map(([id,label])=>`<button type="button" class="learning-chip" data-interview-reason="${id}">${esc(label)}</button>`).join('')}</div><div class="field"><label>Explicação opcional</label><textarea data-interview-text rows="3" data-autogrow placeholder="Escreva com suas palavras, se quiser explicar melhor."></textarea></div><div class="learning-actions"><button type="button" class="primary-button" data-interview-save>Salvar resposta</button><button type="button" class="secondary-button" data-interview-dismiss>Prefiro não responder</button></div></article>`}
function ensurePersonalInterviewUI(){const view=document.querySelector('[data-view="learning"]');if(!view||document.getElementById('personalInterviewSection'))return;const section=document.createElement('section');section.id='personalInterviewSection';section.className='learning-section';section.innerHTML=`<div class="section-title-row"><div><p class="section-kicker">ENTREVISTA PESSOAL</p><h2>Coisas que o app quer entender</h2></div></div><p class="helper">Aqui o motor pergunta sobre fatos que percebeu, mas cuja explicação ele não conhece. Você pode responder, explicar com texto ou simplesmente ignorar.</p><div id="personalInterviewQuestions"></div><div class="analysis-card" id="personalInterviewMemory"><h2>Explicações que você já deu</h2><div id="personalInterviewResponses" class="analysis-stack"></div></div>`;const questions=view.querySelector('.learning-section');questions?.before(section)}
async function renderPersonalInterview(events,meds){ensurePersonalInterviewUI();const box=document.getElementById('personalInterviewQuestions'),memory=document.getElementById('personalInterviewResponses');if(!box||!memory)return;const questions=await personalInterviewQuestions(events,meds),state=personalInterviewState();box.innerHTML=questions.length?questions.map(personalInterviewQuestionHTML).join(''):'<div class="analysis-card"><div class="learning-empty">Nenhuma pergunta pessoal pendente agora.</div></div>';const responses=Object.values(state.responses).sort((a,b)=>new Date(b.answeredAt)-new Date(a.answeredAt)).slice(0,12);memory.innerHTML=responses.length?responses.map(r=>analysisRow(r.periodLabel,r.summary||'Você explicou esse intervalo.')).join(''):analysisRow('Ainda vazio','As explicações que você decidir dar aparecerão aqui e poderão participar do contexto das análises.');
  box.querySelectorAll('[data-interview-question]').forEach(card=>{let selected='';card.querySelectorAll('[data-interview-reason]').forEach(b=>b.onclick=()=>{selected=b.dataset.interviewReason;card.querySelectorAll('[data-interview-reason]').forEach(x=>x.classList.toggle('selected',x===b))});card.querySelector('[data-interview-save]').onclick=async()=>{const q=questions.find(x=>x.key===card.dataset.interviewQuestion);if(!q)return;const text=card.querySelector('[data-interview-text]')?.value.trim()||'',reason=PERSONAL_INTERVIEW_REASONS.find(([id])=>id===selected),summary=[reason?.[1],text].filter(Boolean).join(' — ');if(!summary)return toast('Escolha um motivo, escreva uma explicação ou toque em “Prefiro não responder”.');const st=personalInterviewState();st.responses[q.key]={key:q.key,startKey:q.startKey,gapDays:q.gap,reason:selected||'custom',reasonLabel:reason?.[1]||'',text,summary,periodLabel:q.open?`Intervalo atual de ${Math.floor(q.gap)} dias sem texto`:`Intervalo de ${q.gap.toFixed(1).replace('.',',')} dias sem texto`,startedAt:q.before.timestamp,endedAt:q.after?.timestamp||null,answeredAt:new Date().toISOString()};personalInterviewSave(st);await renderAll();toast('Resposta guardada como contexto relatado por você.')};card.querySelector('[data-interview-dismiss]').onclick=async()=>{const q=questions.find(x=>x.key===card.dataset.interviewQuestion);if(!q)return;const st=personalInterviewState();st.dismissed[q.key]={key:q.key,startKey:q.startKey,at:new Date().toISOString()};personalInterviewSave(st);await renderAll();toast('Pergunta arquivada.')};if(typeof wireAutoGrowTextareas==='function')wireAutoGrowTextareas(card)})}

/* As respostas da entrevista são contexto declarado pelo usuário, mas não entram como eventos temporais de medicamento. */
function personalInterviewAnalysisContext(){const responses=Object.values(personalInterviewState().responses).sort((a,b)=>new Date(b.answeredAt)-new Date(a.answeredAt));if(!responses.length)return'';const recent=responses.slice(0,4),parts=recent.map(r=>{const concepts=typeof learningConceptsInText==='function'?learningConceptsInText([r.reasonLabel,r.text].filter(Boolean).join('. ')).map(c=>learningConceptLabel(c.concept)):[];return`${r.periodLabel}: ${r.summary}${concepts.length?` · conceitos reconhecidos: ${concepts.slice(0,3).join(', ')}`:''}`});return analysisRow('Explicações informadas por você',parts.join(' | '))}
function renderPersonalInterviewAnalysisContext(){const box=document.getElementById('continuityAnalysis');if(!box)return;box.querySelector('[data-interview-context]')?.remove();const html=personalInterviewAnalysisContext();if(html){const wrap=document.createElement('div');wrap.dataset.interviewContext='1';wrap.innerHTML=html;box.appendChild(wrap)}}

/* Histórico: textos longos ficam compactos, mas o cartão continua abrindo a visualização completa. */
const personalInterviewPreviousEventCard=eventCard;
eventCard=function(e){if(e?.type!=='note'||!e.text)return personalInterviewPreviousEventCard(e);const k=kindInfo(e),long=String(e.text).length>150||String(e.text).split(/\n/).length>3;return`<article class="timeline-item ${long?'has-long-note':''}"><div class="timeline-time">${timeLabel(e.timestamp)}</div><div><div class="timeline-kind kind-${k.className}">${k.kind}</div><div class="timeline-title note-preview">${esc(e.text)}</div>${long?'<span class="note-more">Ver mais</span>':''}${k.meta.length?`<div class="timeline-meta">${k.meta.map(esc).join(' · ')}</div>`:''}${e.hasAudio?`<div data-audio="${e.id}"></div>`:''}</div><button class="item-menu" data-menu="${e.id}" aria-label="Opções">•••</button></article>`};

function ensurePersonalInterviewStyles(){if(document.getElementById('personal-interview-style'))return;const st=document.createElement('style');st.id='personal-interview-style';st.textContent=`.interview-reasons{display:flex;gap:7px;flex-wrap:wrap;margin:12px 0}.interview-reasons .learning-chip.selected{background:rgba(116,167,255,.28);outline:1px solid rgba(116,167,255,.42)}.personal-interview-question textarea{min-height:84px}.note-preview{display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:3;overflow:hidden;white-space:normal;line-height:1.35}.note-more{display:inline-block;margin-top:4px;color:var(--accent-color,#7457e8);font-size:12px;font-weight:700}.has-long-note{cursor:pointer}`;document.head.appendChild(st)}

const personalInterviewPreviousRenderAll=renderAll;
renderAll=async function(){await personalInterviewPreviousRenderAll();const events=await allEvents(),meds=await allMedications();await renderPersonalInterview(events,meds);renderPersonalInterviewAnalysisContext()};
function personalInterviewBoot(){ensurePersonalInterviewStyles();ensurePersonalInterviewUI();if(db)renderAll();else setTimeout(personalInterviewBoot,260)}
personalInterviewBoot();
