/* Visualização segura dos registros: tocar abre detalhes; editar exige uma segunda ação explícita. */
function registroDetailDate(value){if(!value)return '—';const d=new Date(value);if(Number.isNaN(d.getTime()))return '—';return d.toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})}
function registroDetailRow(label,value){if(value===null||value===undefined||String(value).trim()==='')return'';return`<div class="analysis-row"><strong>${esc(label)}</strong><span>${esc(String(value))}</span></div>`}
async function openEventViewer(id){const e=(await allEvents()).find(x=>x.id===id);if(!e)return;let title='Detalhes do registro',rows=[];const meds=await allMedications(),m=meds.find(x=>x.id===e.medicationId)||findProfileByEvent(e,meds),p=findPresentation(m,e.presentationId),presentation=p?presentationDisplay(p):'';
if(e.type==='note'){title='Anotação';rows=[registroDetailRow('Anotação',e.text||'Anotação de voz'),registroDetailRow('Tag',e.tag),registroDetailRow('Data e horário',registroDetailDate(e.timestamp))]}
else if(e.type==='medication'){title='Medicamento';rows=[registroDetailRow('Medicamento',e.medication||'Medicamento'),registroDetailRow('Apresentação',presentation),registroDetailRow('Dose',e.dose||(e.totalDoseValue!=null?`${e.totalDoseValue} ${e.doseUnit||''}`.trim():'')),registroDetailRow('Quantidade',e.unitsTaken?`${e.unitsTaken} unidade(s)`:e.quantity),registroDetailRow('Observação',e.note),registroDetailRow('Data e horário',registroDetailDate(e.timestamp))]}
else if(e.type==='sleep'){title='Sono';rows=[registroDetailRow('Dormiu às',registroDetailDate(e.startTime)),registroDetailRow('Acordou às',registroDetailDate(e.endTime)),registroDetailRow('Duração',durationLabel(durationHours(e.startTime,e.endTime))),registroDetailRow('Qualidade percebida',e.quality?`${e.quality} de 5`:''),registroDetailRow('Observações',e.note),registroDetailRow('Origem',e.source==='health-shortcut'?'Importado do app Saúde':'Manual')]}
else if(e.type==='purchase'){title='Compra';rows=[registroDetailRow('Medicamento',e.medication||'Medicamento'),registroDetailRow('Apresentação',presentation),registroDetailRow('Caixas',e.packages),registroDetailRow('Total de unidades',e.totalUnits),registroDetailRow('Valor pago',e.price),registroDetailRow('Onde comprou',e.place),registroDetailRow('Data e horário',registroDetailDate(e.timestamp))]}
else return;
const audio=e.hasAudio?`<div class="analysis-row"><strong>Áudio</strong><span data-audio="${e.id}"></span></div>`:'';
openBackdrop(title,`<div class="analysis-stack">${rows.join('')}${audio}</div><div class="form-actions"><button type="button" class="secondary-button" id="viewerCloseBtn">Fechar</button><button type="button" class="primary-button" id="viewerEditBtn">Editar</button></div>`,ev=>ev.preventDefault());
document.getElementById('viewerCloseBtn').onclick=closeSheet;document.getElementById('viewerEditBtn').onclick=()=>openEventEditor(id);if(e.hasAudio)await hydrateAudio(document.getElementById('form'))}

document.addEventListener('click',e=>{if(e.target.closest('[data-menu],button,audio,input,textarea,select,a'))return;const card=e.target.closest('.timeline-item');if(!card)return;const id=card.querySelector('[data-menu]')?.dataset.menu;if(!id)return;e.preventDefault();e.stopImmediatePropagation();openEventViewer(id)},true);

/* Carrega os motores extras em ordem: Aprendizado -> check-ins/gráficos/revisão -> continuidade. */
(function loadLearningEngine(){if(document.querySelector('script[data-learning-engine]'))return;const s=document.createElement('script');s.dataset.learningEngine='true';s.src='./v04c11.js?v=0.4.4';s.onerror=()=>console.error('Falha ao carregar o motor de Aprendizado');s.onload=()=>{if(document.querySelector('script[data-emotion-engine]'))return;const e=document.createElement('script');e.dataset.emotionEngine='true';e.src='./v04c12.js?v=0.4.5';e.onerror=()=>console.error('Falha ao carregar check-ins e gráficos');e.onload=()=>{if(document.querySelector('script[data-continuity-engine]'))return;const c=document.createElement('script');c.dataset.continuityEngine='true';c.src='./v04c13.js?v=0.4.6';c.onerror=()=>console.error('Falha ao carregar alertas de continuidade');document.head.appendChild(c)};document.head.appendChild(e)};document.head.appendChild(s)})();