/* Alertas por ausência + continuidade como contexto factual para Análises/Aprendizado. */
const CONTINUITY_ENGINE_VERSION='1.0.1';
const DEFAULT_GAP_THRESHOLDS={text:3,mood:2,purchase:45,medication:3,sleep:2};
const GAP_LABELS={text:'texto / observação',mood:'humor',purchase:'compra',medication:'medicamento',sleep:'sono'};

function continuitySettings(){const s=getSettings();return{...DEFAULT_GAP_THRESHOLDS,...(s.inactivityThresholds||{})}}
function saveContinuitySettings(next){const s=getSettings();s.inactivityThresholds=next;saveSettings(s)}
function continuityFirstSeen(){let raw=localStorage.getItem('registro-first-seen');if(!raw){raw=new Date().toISOString();localStorage.setItem('registro-first-seen',raw)}return new Date(raw).getTime()}
function continuityDays(ms){return Math.max(0,ms/86400000)}
function continuityDate(v){return new Date(v).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit',year:'2-digit'})}
function latestTimestamp(list){return list.length?Math.max(...list.map(x=>new Date(x.timestamp).getTime())):null}
function continuityMoodEvents(events){return events.filter(e=>e.type==='note'&&e.moodScore!==null&&e.moodScore!==undefined&&e.moodScore!==''&&Number.isFinite(Number(e.moodScore)))}

async function continuityNarratives(events,meds){const obs=typeof learningCollectObservations==='function'?await learningCollectObservations(events,meds):[];return obs.filter(o=>o.source!=='Tag da anotação'&&String(o.text||'').trim())}
async function continuityLastTimes(events,meds){const narratives=await continuityNarratives(events,meds),moods=continuityMoodEvents(events);return{
  text:latestTimestamp(narratives),
  mood:latestTimestamp(moods),
  purchase:latestTimestamp(events.filter(e=>e.type==='purchase')),
  medication:latestTimestamp(events.filter(e=>e.type==='medication')),
  sleep:latestTimestamp(events.filter(e=>e.type==='sleep'))
}}
async function continuityOverdue(events,meds){const thresholds=continuitySettings(),last=await continuityLastTimes(events,meds),first=continuityFirstSeen(),now=Date.now(),out=[];for(const key of Object.keys(GAP_LABELS)){const threshold=Number(thresholds[key]);if(!Number.isFinite(threshold)||threshold<=0)continue;const base=last[key]??first,gap=continuityDays(now-base);if(gap>=threshold)out.push({key,threshold,gap,last:last[key]})}return out.sort((a,b)=>(b.gap/b.threshold)-(a.gap/a.threshold))}

function ensureContinuityHomeCard(){const home=document.querySelector('[data-view="home"]'),summary=home?.querySelector('.summary-card');if(!home||!summary||document.getElementById('continuityAlertCard'))return;const card=document.createElement('section');card.id='continuityAlertCard';card.className='analysis-card continuity-alert hidden';summary.after(card)}
async function renderContinuityHome(events,meds){ensureContinuityHomeCard();const card=document.getElementById('continuityAlertCard'),items=await continuityOverdue(events,meds);if(!card)return;card.classList.toggle('hidden',!items.length);if(!items.length){card.innerHTML='';return}card.innerHTML=`<div class="continuity-alert-head"><span class="notice-icon" data-icon="clock"></span><div><p class="section-kicker">LEMBRETE DE CONTINUIDADE</p><h2>Faz algum tempo desde alguns registros</h2></div></div><p class="continuity-disclaimer">O app só está observando a frequência dos registros. Um intervalo não significa, por si só, piora de humor, cansaço ou qualquer outro estado.</p><div class="continuity-alert-list">${items.map(i=>`<button type="button" class="continuity-alert-row" data-gap-action="${i.key}"><span><strong>${esc(GAP_LABELS[i.key])}</strong><small>${i.last?`último registro há ${Math.floor(i.gap)} dia(s)`:'ainda sem registro'}</small></span><span>Registrar ›</span></button>`).join('')}</div>`;hydrateIcons(card);card.querySelectorAll('[data-gap-action]').forEach(b=>b.onclick=()=>{const key=b.dataset.gapAction;if(key==='text'||key==='mood')openNoteSheet();else if(key==='purchase')openPurchaseSheet();else if(key==='medication')openMedicationSheet();else if(key==='sleep')openSleepSheet()})}

function openContinuitySettings(){const s=continuitySettings();openBackdrop('Alertas por ausência',`<p class="helper">Defina quantos dias sem cada tipo de registro fazem o cartão aparecer na tela inicial. Use 0 para desativar um alerta.</p>${Object.entries(GAP_LABELS).map(([key,label])=>`<div class="field"><label for="gap-${key}">${esc(label)}</label><div class="inline-unit"><input id="gap-${key}" type="number" min="0" step="1" inputmode="numeric" value="${Number(s[key])}"><span class="continuity-unit">dias</span></div></div>`).join('')}<p class="helper">Esses prazos afetam apenas os lembretes e as análises de continuidade; nunca geram um diagnóstico.</p>${formButtons('Salvar')}`,ev=>{ev.preventDefault();const next={};for(const key of Object.keys(GAP_LABELS))next[key]=Math.max(0,Number(document.getElementById(`gap-${key}`)?.value)||0);saveContinuitySettings(next);closeSheet();renderAll();toast('Prazos atualizados.')})}
function ensureContinuitySettingsUI(){const view=document.querySelector('[data-view="settings"]');if(!view||document.getElementById('continuitySettingsGroup'))return;const groups=[...view.querySelectorAll('.settings-group')],health=groups.find(g=>g.querySelector('h2')?.textContent.includes('Saúde e sono')),group=document.createElement('section');group.id='continuitySettingsGroup';group.className='settings-group';group.innerHTML=`<h2>Continuidade dos registros</h2><div class="settings-card list-card"><button class="settings-row" id="continuitySettingsBtn"><span class="settings-row-icon" data-icon="clock"></span><span><strong>Alertas por ausência</strong><small>Prazos independentes para texto, humor, compras, medicamentos e sono</small></span><span class="chevron">›</span></button></div><p class="group-footnote">O cartão só aparece quando algum prazo configurado é ultrapassado.</p>`;(health||groups[0])?.after(group);hydrateIcons(group);document.getElementById('continuitySettingsBtn').onclick=openContinuitySettings}

function continuityLargestGap(items){const times=[...items].map(x=>new Date(x.timestamp).getTime()).filter(Number.isFinite).sort((a,b)=>a-b);let best=null;for(let i=1;i<times.length;i++){const gap=continuityDays(times[i]-times[i-1]);if(!best||gap>best.gap)best={gap,start:times[i-1],end:times[i]}}return best}
function continuityQualifyingGaps(items,threshold){const sorted=[...items].sort((a,b)=>new Date(a.timestamp)-new Date(b.timestamp)),out=[];for(let i=1;i<sorted.length;i++){const gap=continuityDays(new Date(sorted[i].timestamp)-new Date(sorted[i-1].timestamp));if(gap>=threshold)out.push({gap,before:sorted[i-1],after:sorted[i]})}return out}
function continuityConceptLabels(text){if(typeof learningConceptsInText!=='function')return[];return learningConceptsInText(text).map(c=>learningConceptLabel(c.concept))}
function ensureContinuityAnalysisCard(){const view=document.querySelector('[data-view="analysis"]');if(!view||document.getElementById('continuityAnalysisCard'))return;const anchor=document.createElement('span');anchor.hidden=true;anchor.dataset.analysisHomeAnchor='analysis-continuity';const card=document.createElement('section');card.id='continuityAnalysisCard';card.className='analysis-card analysis-review-item';card.dataset.analysisItem='analysis-continuity';card.innerHTML=`<div class="analysis-title"><span data-icon="clock"></span><h2>Continuidade dos registros</h2></div><div id="continuityAnalysis" class="analysis-stack"></div>`;const sleep=document.getElementById('sleepAnalysis')?.closest('.analysis-card');if(sleep){sleep.after(anchor);anchor.after(card)}else{view.append(anchor,card)}if(typeof ANALYSIS_REVIEW_DEFS!=='undefined')ANALYSIS_REVIEW_DEFS['analysis-continuity']='Continuidade dos registros';if(!card.querySelector('[data-analysis-review]')){const b=document.createElement('button');b.type='button';b.className='chart-review-btn floating-review';b.dataset.analysisReview='analysis-continuity';b.textContent='Avaliar';card.appendChild(b)}hydrateIcons(card)}
async function renderContinuityAnalysis(events,meds){ensureContinuityAnalysisCard();const box=document.getElementById('continuityAnalysis');if(!box)return;const narratives=await continuityNarratives(events,meds),moods=continuityMoodEvents(events),overdue=await continuityOverdue(events,meds),settings=continuitySettings(),largestText=continuityLargestGap(narratives),largestMood=continuityLargestGap(moods),rows=[];if(overdue.length)rows.push(analysisRow('Intervalos atuais',overdue.map(i=>`${GAP_LABELS[i.key]}: ${Math.floor(i.gap)} dia(s)`).join(' · ')));else rows.push(analysisRow('Intervalos atuais','Nenhum dos prazos configurados foi ultrapassado.'));if(largestText)rows.push(analysisRow('Maior intervalo entre textos',`${largestText.gap.toFixed(1).replace('.',',')} dia(s), de ${continuityDate(largestText.start)} a ${continuityDate(largestText.end)}`));if(largestMood)rows.push(analysisRow('Maior intervalo entre notas de humor',`${largestMood.gap.toFixed(1).replace('.',',')} dia(s), de ${continuityDate(largestMood.start)} a ${continuityDate(largestMood.end)}`));const textThreshold=Number(settings.text)||0,gaps=textThreshold>0?continuityQualifyingGaps(narratives,textThreshold):[],conceptCounts={},examples=[];for(const g of gaps){const concepts=continuityConceptLabels(g.after.text);for(const c of concepts)conceptCounts[c]=(conceptCounts[c]||0)+1;if(concepts.length&&examples.length<2)examples.push({gap:g.gap,concepts,text:g.after.text})}const recurrent=Object.entries(conceptCounts).sort((a,b)=>b[1]-a[1]).filter(([,n])=>n>=2).slice(0,3);if(gaps.length&&recurrent.length)rows.push(analysisRow('Padrão nas retomadas',`Após ${gaps.length} intervalo(s) de pelo menos ${settings.text} dia(s), os primeiros relatos repetiram termos ligados a ${recurrent.map(([c,n])=>`${c} (${n})`).join(', ')}. Isso descreve os relatos após os intervalos; não explica por que você parou de registrar.`));else if(examples.length)rows.push(analysisRow('Contexto após um intervalo',`Depois de um intervalo de ${examples[0].gap.toFixed(1).replace('.',',')} dia(s), o primeiro texto continha termos ligados a ${examples[0].concepts.slice(0,3).join(', ')}. O app trata isso apenas como contexto temporal.`));box.innerHTML=rows.join('');if(typeof applyAnalysisReviewPlacement==='function')applyAnalysisReviewPlacement()}

function ensureContinuityLearningCard(){const view=document.querySelector('[data-view="learning"]');if(!view||document.getElementById('learningContinuityCard'))return;const card=document.createElement('section');card.id='learningContinuityCard';card.className='analysis-card';card.innerHTML=`<p class="section-kicker">CONTEXTO TEMPORAL</p><h2>Intervalos sem registrar também contam</h2><div id="learningContinuityText" class="analysis-stack"></div>`;const explain=view.querySelector('.learning-explain');(explain||view.lastElementChild)?.before(card)}
async function renderContinuityLearning(events,meds){ensureContinuityLearningCard();const box=document.getElementById('learningContinuityText');if(!box)return;const items=await continuityOverdue(events,meds),settings=continuitySettings();box.innerHTML=[analysisRow('O que o app observa','Ele mede quanto tempo passa entre registros e usa isso como contexto, sem transformar ausência em sintoma.'),analysisRow('Prazos atuais',Object.entries(settings).map(([k,v])=>`${GAP_LABELS[k]}: ${v===0?'desativado':`${v} dia(s)`}`).join(' · ')),analysisRow('Agora',items.length?items.map(i=>`${GAP_LABELS[i.key]} há ${Math.floor(i.gap)} dia(s)`).join(' · '):'Nenhum prazo ultrapassado.')].join('')}

function ensureContinuityStyles(){if(document.getElementById('continuity-style'))return;const st=document.createElement('style');st.id='continuity-style';st.textContent=`.continuity-alert{margin:14px 0;border:1px solid rgba(255,159,10,.22)}.continuity-alert-head{display:flex;gap:10px;align-items:flex-start}.continuity-disclaimer{font-size:12px;line-height:1.45;opacity:.66;margin:8px 0 12px}.continuity-alert-list{display:grid;gap:8px}.continuity-alert-row{width:100%;display:flex;align-items:center;justify-content:space-between;gap:12px;text-align:left;border:0;border-radius:14px;padding:11px 12px;background:rgba(120,120,128,.08);color:inherit}.continuity-alert-row span:first-child{display:flex;flex-direction:column;gap:2px}.continuity-alert-row small{font-size:11px;opacity:.62}.continuity-unit{padding:0 8px;opacity:.65}.analysis-review-item{position:relative}`;document.head.appendChild(st)}

/* Corrige a leitura quantitativa: ausência de nota não vale 0/10. */
if(typeof analysisMoodNotes==='function')analysisMoodNotes=function(events){return events.filter(e=>e.type==='note'&&e.moodScore!==null&&e.moodScore!==undefined&&e.moodScore!==''&&Number.isFinite(Number(e.moodScore))).map(e=>({...e,moodScore:Number(e.moodScore)})).sort((a,b)=>new Date(a.timestamp)-new Date(b.timestamp))};

const continuityPreviousRenderAll=renderAll;
renderAll=async function(){await continuityPreviousRenderAll();const events=await allEvents(),meds=await allMedications();ensureContinuitySettingsUI();await renderContinuityHome(events,meds);await renderContinuityAnalysis(events,meds);await renderContinuityLearning(events,meds)};
function continuityBoot(){ensureContinuityStyles();ensureContinuityHomeCard();ensureContinuitySettingsUI();ensureContinuityAnalysisCard();ensureContinuityLearningCard();if(db)renderAll();else setTimeout(continuityBoot,240)}
continuityBoot();
