/* Visualização segura dos registros: tocar abre detalhes; editar exige uma segunda ação explícita. */
function registroDetailDate(value){if(!value)return '—';const d=new Date(value);if(Number.isNaN(d.getTime()))return '—';return d.toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})}
function registroDetailRow(label,value){if(value===null||value===undefined||String(value).trim()==='')return'';return`<div class="analysis-row"><strong>${esc(label)}</strong><span>${esc(String(value))}</span></div>`}
async function openEventViewer(id){const e=(await allEvents()).find(x=>x.id===id);if(!e)return;let title='Detalhes do registro',rows=[];const meds=await allMedications(),m=meds.find(x=>x.id===e.medicationId)||findProfileByEvent(e,meds),p=findPresentation(m,e.presentationId),presentation=p?presentationDisplay(p):'';
if(e.type==='note'){title='Anotação';rows=[registroDetailRow('Anotação',e.text||'Anotação de voz'),registroDetailRow('Tag',e.tag),registroDetailRow('Data e horário',registroDetailDate(e.timestamp))]}
else if(e.type==='medication'){title='Medicamento';rows=[registroDetailRow('Medicamento',e.medication||'Medicamento'),registroDetailRow('Apresentação',presentation),registroDetailRow('Dose',e.dose||(e.totalDoseValue!=null?`${e.totalDoseValue} ${e.doseUnit||''}`.trim():'')),registroDetailRow('Quantidade',e.unitsTaken?`${e.unitsTaken} unidade(s)`:e.quantity),registroDetailRow('Observação',e.note),registroDetailRow('Data e horário',registroDetailDate(e.timestamp))]}
else if(e.type==='sleep'){title='Sono';rows=[registroDetailRow('Dormiu às',registroDetailDate(e.startTime)),registroDetailRow('Acordou às',registroDetailDate(e.endTime)),registroDetailRow('Duração',durationLabel(durationHours(e.startTime,e.endTime))),registroDetailRow('Qualidade percebida',e.quality?`${e.quality} de 5`:''),registroDetailRow('Observações',e.note),registroDetailRow('Origem',e.source==='health-shortcut'?'Importado do app Saúde':'Manual')]}
else if(e.type==='purchase'){title='Compra';rows=[registroDetailRow('Medicamento',e.medication||'Medicamento'),registroDetailRow('Apresentação',presentation),registroDetailRow('Caixas',e.packages),registroDetailRow('Total de unidades',e.totalUnits),registroDetailRow('Valor pago',e.price),registroDetailRow('Onde comprou',e.place),registroDetailRow('Data e horário',registroDetailDate(e.timestamp))]}
else return;
const audio=e.hasAudio?`<div class="analysis-row"><strong>Áudio</strong><span data-audio="${e.id}"></span></div>`:'';
openBackdrop(title,`<div class="analysis-stack">${rows.join('')}${audio}</div><div class="form-actions"><button type="button" class="secondary-button" id="viewerCloseBtn">Fechar</button><button type="button" class="primary-button" id="viewerEditBtn">Editar</button></div>`,ev=>ev.preventDefault());
document.getElementById('viewerCloseBtn').onclick=closeSheet;document.getElementById('viewerEditBtn').onclick=()=>openEventEditor(id);if(e.hasAudio)await hydrateAudio(document.getElementById('form'))}

document.addEventListener('click',e=>{if(e.target.closest('[data-menu],button,audio,input,textarea,select,a'))return;const card=e.target.closest('.timeline-item');if(!card)return;const id=card.querySelector('[data-menu]')?.dataset.menu;if(!id)return;e.preventDefault();e.stopImmediatePropagation();openEventViewer(id)},true);

/* Cores semânticas: o mesmo tipo de registro mantém a mesma identidade em todas as telas. */
(function ensureSemanticIconColors(){if(document.getElementById('semantic-icon-colors'))return;const st=document.createElement('style');st.id='semantic-icon-colors';st.textContent=`
[data-icon="note"]{color:var(--accent)!important}
[data-icon="pill"]{color:var(--med)!important}
[data-icon="moon"]{color:var(--sleep)!important}
[data-icon="bag"]{color:var(--buy)!important}
`;document.head.appendChild(st)})();

/* Carrega os motores extras em ordem: Aprendizado -> check-ins/gráficos/revisão -> continuidade -> entrevista pessoal -> paletas semânticas -> ícones preenchidos -> acabamento do humor -> sistema visual global. */
(function loadLearningEngine(){if(document.querySelector('script[data-learning-engine]'))return;const s=document.createElement('script');s.dataset.learningEngine='true';s.src='./v04c11.js?v=0.4.4';s.onerror=()=>console.error('Falha ao carregar o motor de Aprendizado');s.onload=()=>{if(document.querySelector('script[data-emotion-engine]'))return;const e=document.createElement('script');e.dataset.emotionEngine='true';e.src='./v04c12.js?v=0.4.5';e.onerror=()=>console.error('Falha ao carregar check-ins e gráficos');e.onload=()=>{if(document.querySelector('script[data-continuity-engine]'))return;const c=document.createElement('script');c.dataset.continuityEngine='true';c.src='./v04c13.js?v=0.4.6';c.onerror=()=>console.error('Falha ao carregar alertas de continuidade');c.onload=()=>{if(document.querySelector('script[data-interview-engine]'))return;const i=document.createElement('script');i.dataset.interviewEngine='true';i.src='./v04c14.js?v=0.4.7';i.onerror=()=>console.error('Falha ao carregar entrevista pessoal');i.onload=()=>{if(document.querySelector('script[data-semantic-palette-engine]'))return;const p=document.createElement('script');p.dataset.semanticPaletteEngine='true';p.src='./v04c15.js?v=0.4.14';p.onerror=()=>console.error('Falha ao carregar paletas semânticas');p.onload=()=>{if(document.querySelector('script[data-record-icons-engine]'))return;const r=document.createElement('script');r.dataset.recordIconsEngine='true';r.src='./v04c16.js?v=0.4.11';r.onerror=()=>console.error('Falha ao carregar ícones preenchidos de registros');r.onload=()=>{if(document.querySelector('script[data-mood-visual-engine]'))return;const m=document.createElement('script');m.dataset.moodVisualEngine='true';m.src='./v04c17.js?v=0.4.16';m.onerror=()=>console.error('Falha ao carregar acabamento visual do humor');m.onload=()=>{if(document.querySelector('script[data-rm-visual-engine]'))return;const v=document.createElement('script');v.dataset.rmVisualEngine='true';v.src='./v04c18.js?v=0.4.17';v.onerror=()=>console.error('Falha ao carregar o sistema visual global');document.head.appendChild(v)};document.head.appendChild(m)};document.head.appendChild(r)};document.head.appendChild(p)};document.head.appendChild(i)};document.head.appendChild(c)};document.head.appendChild(e)};document.head.appendChild(s)})();
