function openPresentationEditor(m){openBackdrop('Nova apresentação',`<div class="field-grid"><div class="field"><label>Dosagem</label><input id="pStrength" inputmode="decimal"></div><div class="field"><label>Unidade</label><select id="pUnit"><option>mg</option><option>mcg</option><option>g</option><option>mL</option></select></div></div><div class="field"><label>Forma</label><input id="pForm" placeholder="cápsula, comprimido…"></div><div class="field"><label>Marca opcional</label><input id="pBrand" value="${esc(m.referenceName||'')}"></div><div class="field"><label>Laboratório opcional</label><input id="pLab" value="${esc(m.lab||'')}"></div><div class="field-grid"><div class="field"><label>Unidades por caixa</label><input id="pUnits" inputmode="numeric"></div><div class="field"><label>Unidades por cartela</label><input id="pBlister" inputmode="numeric"></div></div>${formButtons('Adicionar')}`,async ev=>{ev.preventDefault();const strength=document.getElementById('pStrength').value.trim();if(!strength)return toast('Informe a dosagem.');m.presentations=[...(m.presentations||[]),{id:uid('presentation'),strengthValue:Number(String(strength).replace(',','.'))||strength,strengthUnit:document.getElementById('pUnit').value,form:document.getElementById('pForm').value.trim(),brand:document.getElementById('pBrand').value.trim(),lab:document.getElementById('pLab').value.trim(),unitsPerPackage:Number(document.getElementById('pUnits').value)||'',unitsPerBlister:Number(document.getElementById('pBlister').value)||''}];await putMedication(m);toast('Apresentação adicionada.');openMedicationDetail(m.id)})}

function openCustomIcons(){const keys=['home','history','chart','settings','note','pill','moon','bag','spark','link','heart','export','import'];openBackdrop('Substituir ícones',`<p class="helper">Escolha um ícone do app. Você pode apontá-lo para outro código do banco interno ou importar um SVG. SVG é texto XML e entra no backup JSON.</p><div class="icon-editor-grid">${keys.map(k=>`<button type="button" class="icon-choice" data-icon-edit="${k}"><span class="preview">${svg(k)}</span><span>${k}</span></button>`).join('')}</div>${formButtons('Fechar')}`);document.querySelectorAll('[data-icon-edit]').forEach(b=>b.onclick=()=>openIconEditor(b.dataset.iconEdit))}
function openIconEditor(key){iconEditorTarget=key;const current=getSettings().iconOverrides?.[key];openBackdrop(`Ícone: ${key}`,`<div class="svg-editor-preview" id="iconPreview">${svg(key)}</div><div class="field"><label>Código do banco interno</label><input id="bankIconCode" placeholder="Ex.: moon, pill, home" value="${esc(current?.type==='bank'?current.value:'')}"></div><p class="helper">Códigos disponíveis: ${Object.keys(baseIcons).join(', ')}.</p><div class="field"><label>Ou conteúdo SVG</label><textarea id="svgIconText" placeholder="Cole o &lt;svg&gt;…&lt;/svg&gt; ou apenas os paths">${esc(current?.type==='svg'?current.value:'')}</textarea></div><div class="registry-toolbar"><button type="button" class="secondary-button" id="chooseSvgFile">Escolher arquivo SVG</button><button type="button" class="secondary-button" id="resetIconBtn">Restaurar</button></div>${formButtons('Salvar ícone')}`,ev=>{ev.preventDefault();const bank=document.getElementById('bankIconCode').value.trim(),raw=document.getElementById('svgIconText').value.trim(),s=getSettings();s.iconOverrides={...(s.iconOverrides||{})};if(raw)s.iconOverrides[key]={type:'svg',value:raw};else if(bank&&baseIcons[bank])s.iconOverrides[key]={type:'bank',value:bank};else if(bank)return toast('Código de ícone desconhecido.');else delete s.iconOverrides[key];saveSettings(s);toast('Ícone atualizado.');openCustomIcons()});document.getElementById('chooseSvgFile').onclick=()=>document.getElementById('svgImportFile').click();document.getElementById('resetIconBtn').onclick=()=>{const s=getSettings();s.iconOverrides={...(s.iconOverrides||{})};delete s.iconOverrides[key];saveSettings(s);toast('Ícone restaurado.');openCustomIcons()}}

function renderBackupState(){const last=localStorage.getItem(LAST_BACKUP_KEY),status=document.getElementById('backupStatusText'),warning=document.getElementById('backupWarning'),text=document.getElementById('backupWarningText');if(!status||!warning)return;if(!last){status.textContent='Nenhum backup externo criado';warning.classList.remove('hidden');text.textContent='Você ainda não criou um backup externo.';return}const days=(Date.now()-new Date(last))/86400000;status.textContent=`Último backup ${humanAgo(last)}`;warning.classList.toggle('hidden',days<BACKUP_WARN_DAYS);if(days>=BACKUP_WARN_DAYS)text.textContent=`O último backup foi criado há ${Math.floor(days)} dias.`}
function renderHealthState(){const last=localStorage.getItem(LAST_HEALTH_IMPORT_KEY),el=document.getElementById('healthStatusText');if(el)el.textContent=last?`Última importação ${humanAgo(last)}`:'Não configurado neste aparelho'}
async function exportData(){const payload={app:'Registro',version:APP_VERSION,exportedAt:new Date().toISOString(),events:await allEvents(),medications:await allMedications(),settings:getSettings()},blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`registro-backup-${localDate(new Date())}.json`;document.body.appendChild(a);a.click();a.remove();localStorage.setItem(LAST_BACKUP_KEY,new Date().toISOString());setTimeout(()=>URL.revokeObjectURL(a.href),1000);renderBackupState();toast('Backup criado.')}
async function importData(file){try{const data=JSON.parse(await file.text()),events=Array.isArray(data)?data:data.events;if(Array.isArray(events))for(const e of events){if(e?.id&&['note','medication','sleep','purchase'].includes(e.type)&&e.timestamp)await putEvent(e)}if(Array.isArray(data.medications))for(const m of data.medications)if(m?.id&&m.activeIngredient)await putMedication(m);if(data.settings&&typeof data.settings==='object')saveSettings({...getSettings(),...data.settings});await renderAll();toast('Backup importado.')}catch{toast('Arquivo de backup inválido.')}}
async function restoreDemo(){if(!confirm('Substituir todos os registros pelos dados fictícios?'))return;for(const e of await allEvents())await deleteEvent(e.id);for(const e of demoEvents())await putEvent(e);localStorage.setItem('registro-demo-seeded','yes');await renderAll();toast('Dados fictícios restaurados.')}
async function clearData(){if(!confirm('Apagar todos os registros e cadastros deste aparelho?'))return;await req(store(EVENTS,'readwrite').clear());await req(store(AUDIO,'readwrite').clear());await req(store(MEDICATIONS,'readwrite').clear());localStorage.setItem('registro-demo-seeded','yes');await renderAll();toast('Dados locais apagados.')}

function healthImportInfo(){openBackdrop('Sono do app Saúde',`<div class="analysis-row"><strong>Atalho como ponte</strong><span>O Atalho lê o sono no app Saúde e abre este PWA com os horários. “Revisar” continua sendo o modo recomendado.</span></div><p class="helper">O botão + Sono permanece disponível e os dados importados podem ser corrigidos.</p>${formButtons('Fechar')}`)}

/* Edição de registros e proteção contra salvamento acidental pelo Enter */
function editSetValue(id,value,events=true){const el=document.getElementById(id);if(!el)return;el.value=value??'';if(events){el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}))}}
function editIsoFromField(id){const value=document.getElementById(id)?.value;if(!value)return null;const d=new Date(value);return Number.isNaN(d.getTime())?null:d.toISOString()}
function editNumber(id){const raw=String(document.getElementById(id)?.value??'').trim();if(!raw)return null;const n=Number(raw.replace(',','.'));return Number.isFinite(n)?n:null}
function editTitle(type){return type==='note'?'Editar anotação':type==='medication'?'Editar medicamento':type==='sleep'?'Editar sono':'Editar compra'}
function finishEventEditor(existing){const form=document.getElementById('form');document.getElementById('sheetTitle').textContent=editTitle(existing.type);const submit=form.querySelector('button[type="submit"]');if(submit)submit.textContent='Salvar alterações';form.onsubmit=ev=>saveEditedEvent(ev,existing)}

async function openEventEditor(id){const existing=(await allEvents()).find(x=>x.id===id);if(!existing)return;
  if(existing.type==='note'){
    await openNoteSheet();
    editSetValue('noteText',existing.text||'',false);editSetValue('noteTag',existing.tag||'',false);editSetValue('recordTime',toLocalInput(existing.timestamp));
  }else if(existing.type==='medication'){
    await openMedicationSheet();
    editSetValue('medName',existing.medication||'',false);editSetValue('medNote',existing.note||'',false);editSetValue('recordTime',toLocalInput(existing.timestamp));
    const meds=await allMedications(),m=meds.find(x=>x.id===existing.medicationId)||findProfileByEvent(existing,meds);
    if(m){selectedMedicationId=m.id;const field=document.getElementById('presentationField'),sel=document.getElementById('presentationSelect');field?.classList.remove('hidden');if(sel){sel.innerHTML=presentationOptions(m);sel.value=existing.presentationId||'';selectedPresentationId=sel.value||null;sel.onchange=async()=>{selectedPresentationId=sel.value||null;const activeMode=document.querySelector('[data-dose-mode].selected')?.dataset.doseMode||'perUnit';await renderDoseFields(activeMode)}}}
    const mode=existing.doseMode||(existing.unitDoseValue!=null?'perUnit':'total'),modeBtn=document.querySelector(`[data-dose-mode="${mode}"]`);if(modeBtn){modeBtn.click();await new Promise(r=>requestAnimationFrame(()=>r()))}else await renderDoseFields(mode);
    editSetValue('doseUnit',existing.doseUnit||'mg');
    if(mode==='total')editSetValue('totalDoseValue',existing.totalDoseValue??(parseFloat(existing.dose)||''));else{const units=Number(existing.unitsTaken)||1;const unitDose=existing.unitDoseValue!=null?existing.unitDoseValue:(existing.totalDoseValue!=null?Number(existing.totalDoseValue)/units:'');editSetValue('unitDoseValue',unitDose);editSetValue('unitsTaken',units)}
  }else if(existing.type==='purchase'){
    await openPurchaseSheet();
    editSetValue('purchaseMed',existing.medication||'',false);editSetValue('purchasePackages',existing.packages||1);editSetValue('purchasePrice',existing.price||'');editSetValue('purchasePlace',existing.place||'',false);editSetValue('recordTime',toLocalInput(existing.timestamp));
    const meds=await allMedications(),m=meds.find(x=>x.id===existing.medicationId)||findProfileByEvent(existing,meds);
    if(m){selectedMedicationId=m.id;const field=document.getElementById('purchasePresentationField'),sel=document.getElementById('purchasePresentation');field?.classList.remove('hidden');if(sel){sel.innerHTML=presentationOptions(m);sel.value=existing.presentationId||'';selectedPresentationId=sel.value||null;sel.onchange=()=>{selectedPresentationId=sel.value||null;updatePurchasePreview()}}}
    await updatePurchasePreview();
  }else if(existing.type==='sleep'){
    openSleepSheet();editSetValue('sleepStart',toLocalInput(existing.startTime));editSetValue('sleepEnd',toLocalInput(existing.endTime));editSetValue('sleepNote',existing.note||'',false);const q=Number(existing.quality)||4;document.querySelector(`#sleepQuality [data-quality="${q}"]`)?.click();
  }else return;
  finishEventEditor(existing)
}

async function saveEditedEvent(ev,existing){ev.preventDefault();let record={...existing};
  if(existing.type==='note'){
    const text=document.getElementById('noteText').value.trim(),timestamp=editIsoFromField('recordTime');if(!text&&!pendingAudio&&!existing.hasAudio)return toast('Escreva ou grave uma anotação.');if(!timestamp)return toast('Informe uma data e horário válidos.');const hasAudio=Boolean(existing.hasAudio||pendingAudio);record={...existing,timestamp,text,tag:document.getElementById('noteTag').value.trim(),hasAudio,audioOnly:Boolean(hasAudio&&!text)};
  }else if(existing.type==='medication'){
    const name=document.getElementById('medName').value.trim(),timestamp=editIsoFromField('recordTime');if(!name)return toast('Informe o medicamento.');if(!timestamp)return toast('Informe uma data e horário válidos.');const mode=document.querySelector('[data-dose-mode].selected')?.dataset.doseMode||'perUnit',unit=document.getElementById('doseUnit')?.value||'mg';let totalDoseValue,unitsTaken=1,unitDoseValue=null;if(mode==='total'){totalDoseValue=editNumber('totalDoseValue');if(totalDoseValue==null)return toast('Informe a dose total.')}else{unitDoseValue=editNumber('unitDoseValue');unitsTaken=editNumber('unitsTaken')??1;if(unitDoseValue==null)return toast('Informe a dose de cada unidade.');totalDoseValue=unitDoseValue*unitsTaken}record={...existing,timestamp,medication:name,medicationId:selectedMedicationId||null,presentationId:selectedPresentationId||null,doseMode:mode,unitDoseValue,totalDoseValue,doseUnit:unit,unitsTaken,dose:`${totalDoseValue.toLocaleString('pt-BR')} ${unit}`,quantity:unitsTaken===1?'1 unidade':`${unitsTaken} unidades`,note:document.getElementById('medNote').value.trim()};
  }else if(existing.type==='purchase'){
    const name=document.getElementById('purchaseMed').value.trim(),timestamp=editIsoFromField('recordTime');if(!name)return toast('Informe o medicamento.');if(!timestamp)return toast('Informe uma data e horário válidos.');const packages=Math.max(1,editNumber('purchasePackages')??1),meds=await allMedications(),m=meds.find(x=>x.id===selectedMedicationId),p=findPresentation(m,selectedPresentationId),samePresentation=selectedPresentationId===existing.presentationId,upp=Number(p?.unitsPerPackage)||(samePresentation?Number(existing.unitsPerPackage):0);record={...existing,timestamp,medication:name,medicationId:selectedMedicationId||null,presentationId:selectedPresentationId||null,packages,totalUnits:upp?packages*upp:null,unitsPerPackage:upp||null,price:document.getElementById('purchasePrice').value.trim(),place:document.getElementById('purchasePlace').value.trim()};
  }else if(existing.type==='sleep'){
    const start=new Date(document.getElementById('sleepStart').value),end=new Date(document.getElementById('sleepEnd').value);if(!(start<end))return toast('O horário de acordar precisa ser posterior ao horário de dormir.');record={...existing,timestamp:end.toISOString(),startTime:start.toISOString(),endTime:end.toISOString(),quality:Number(document.getElementById('sleepQualityValue').value)||4,note:document.getElementById('sleepNote').value.trim()};
  }
  await putEvent(record);if(existing.type==='note'&&pendingAudio)await saveAudio(existing.id,pendingAudio);closeSheet();await renderAll();toast('Alterações salvas.')
}

openEventMenu=async function(id){const existing=(await allEvents()).find(x=>x.id===id);if(!existing)return;openBackdrop('Opções do registro',`<div class="sheet-options"><button type="button" class="sheet-option" id="editEventBtn">Editar registro</button><button type="button" class="sheet-option danger" id="deleteBtn">Excluir registro</button></div>${formButtons('Fechar')}`,(ev)=>{ev.preventDefault();closeSheet()});document.getElementById('editEventBtn').onclick=()=>openEventEditor(id);document.getElementById('deleteBtn').onclick=async()=>{if(confirm('Excluir este registro?')){await deleteEvent(id);closeSheet();await renderAll();toast('Registro excluído.')}}}

const registroForm=document.getElementById('form');registroForm?.addEventListener('keydown',e=>{if(e.key!=='Enter'||e.isComposing)return;const target=e.target;if(target instanceof HTMLTextAreaElement)return;if(target instanceof HTMLInputElement||target instanceof HTMLSelectElement){e.preventDefault();e.stopPropagation();target.blur();document.getElementById('medAutocomplete')?.classList.add('hidden')}},true);

document.addEventListener('click',e=>{if(e.target.closest('[data-menu],button,audio,input,textarea,select,a'))return;const card=e.target.closest('.timeline-item');if(!card)return;const id=card.querySelector('[data-menu]')?.dataset.menu;if(id)openEventEditor(id)});
