/* Aprendizado local: vocabulário pessoal + perguntas de confirmação + análise de todo texto observacional. */
const LEARNING_ENGINE_VERSION='1.0.0';
const LEARNING_CONCEPTS={
  ansiedade:'Ansiedade',humor_negativo:'Humor negativo',humor_positivo:'Humor positivo',calma:'Calma',
  sonolencia:'Sonolência',cansaco:'Cansaço / baixa energia',concentracao:'Concentração / atenção',
  agitacao:'Agitação',irritabilidade:'Irritabilidade',confusao:'Confusão / lentificação',
  nausea:'Náusea / enjoo',tontura:'Tontura',dor_cabeca:'Dor de cabeça',insonia:'Insônia',apetite:'Apetite'
};
const LEARNING_BASE_LEXICON={
  ansiedade:['ansiedade','ansioso','ansiosa','aflito','aflita','aflicao','agonia','nervoso','nervosa','panico','preocupado','preocupada'],
  humor_negativo:['triste','tristeza','desanimado','desanimada','deprimido','deprimida','pessimo','pessima','mal','vazio','vazia','sem esperanca'],
  humor_positivo:['feliz','felicidade','animado','animada','otimo','otima','bem','empolgado','empolgada'],
  calma:['calmo','calma','tranquilo','tranquila','relaxado','relaxada'],
  sonolencia:['sono','sonolento','sonolenta','sonolencia','grogue','sedado','sedada','bocejando','apagando'],
  cansaco:['cansado','cansada','cansaco','exausto','exausta','exaustao','fadiga','sem energia'],
  concentracao:['foco','concentrado','concentrada','concentracao','distraido','distraida','disperso','dispersa','sem foco'],
  agitacao:['agitado','agitada','agitacao','acelerado','acelerada','inquieto','inquieta'],
  irritabilidade:['irritado','irritada','irritabilidade','raiva','impaciente'],
  confusao:['confuso','confusa','confusao','lerdo','lerda','lento','lenta','lentidao'],
  nausea:['nausea','enjoado','enjoada','enjoo'],
  tontura:['tontura','tonto','tonta','vertigem'],
  dor_cabeca:['dor de cabeca','cefaleia','enxaqueca'],
  insonia:['insonia','sem dormir','nao consegui dormir','dificuldade para dormir'],
  apetite:['apetite','fome','sem fome']
};
const LEARNING_STOPWORDS=new Set(('a o os as um uma uns umas de da do das dos em no na nos nas por para com sem e ou mas que se eu meu minha meus minhas voce voces ele ela eles elas isso isto aquilo esse essa esses essas ao aos ate desde entre sobre como quando onde porque pois entao ainda tambem muito muita muitos muitas pouco pouca poucos poucas mais menos ja agora hoje ontem amanha aqui ali la depois antes durante foi fui era estou estava estou estou tenho tinha tive tem ter ser estar fazer fiz fez vou vai vamos pra pro pela pelo pelas pelos cada todo toda todos todas algum alguma alguns algumas nenhum nenhuma mesmo mesma mesmo assim so apenas realmente meio quase tipo coisa coisas vez vezes dia dias hora horas minuto minutos momento momentos tomei tomar tomado tomando medicamento remedio remedios comprimido comprimidos capsula capsulas dose doses mg mcg ml g unidade unidades caixa caixas minha meu seu sua nao nem nunca nada me mim te lhe deles delas nossa nosso voce').split(' '));
const LEARNING_NEGATIONS=new Set(['nao','nem','nunca','sem']);

function learningState(){const s=getSettings(),raw=s.learning||{};return{version:1,terms:{...(raw.terms||{})},ignored:{...(raw.ignored||{})},rejected:{...(raw.rejected||{})},postponed:{...(raw.postponed||{})}}}
function learningSaveState(state){const s=getSettings();s.learning={...state,version:1};saveSettings(s)}
function learningConceptLabel(key){return LEARNING_CONCEPTS[key]||key}
function learningContainsPhrase(norm,phrase){const p=normalizeText(phrase);return (` ${norm} `).includes(` ${p} `)}
function learningPhraseNegated(norm,phrase){const p=normalizeText(phrase),idx=(` ${norm} `).indexOf(` ${p} `);if(idx<0)return false;const before=norm.slice(0,Math.max(0,idx-1)).trim().split(/\s+/).filter(Boolean).slice(-4);return before.some(x=>LEARNING_NEGATIONS.has(x))}
function learningBaseLookup(){const out={};Object.entries(LEARNING_BASE_LEXICON).forEach(([concept,terms])=>terms.forEach(term=>out[normalizeText(term)]={concept,display:term}));return out}
const LEARNING_BASE_LOOKUP=learningBaseLookup();

function learningMappings(){const state=learningState(),maps=[];
  Object.entries(state.terms).forEach(([term,data])=>{if(data?.concept&&data.concept!=='ignore')maps.push({term,concept:data.concept,source:'user'})});
  Object.entries(LEARNING_BASE_LOOKUP).forEach(([term,data])=>{const user=state.terms[term];if(user)return;if(state.ignored[term])return;if(state.rejected[`${term}|${data.concept}`])return;maps.push({term,concept:data.concept,source:'base'})});
  return maps.sort((a,b)=>b.term.length-a.term.length)
}
function learningConceptsInText(text=''){const norm=normalizeText(text);if(!norm)return[];const found=new Map();for(const m of learningMappings()){if(!learningContainsPhrase(norm,m.term))continue;if(learningPhraseNegated(norm,m.term))continue;const current=found.get(m.concept)||{concept:m.concept,count:0,terms:[]};current.count++;current.terms.push(m.term);found.set(m.concept,current)}return[...found.values()]}

async function learningCollectObservations(events=null,meds=null){events=events||await allEvents();meds=meds||await allMedications();const out=[];
  const add=(text,timestamp,source,eventId=null,medicationId=null)=>{text=String(text||'').trim();if(!text)return;out.push({text,timestamp:timestamp||new Date().toISOString(),source,eventId,medicationId})};
  for(const e of events){if(e.type==='note'){add(e.text,e.timestamp,'Anotação',e.id);add(e.tag,e.timestamp,'Tag da anotação',e.id)}else if(e.type==='medication')add(e.note,e.timestamp,'Observação da tomada',e.id,e.medicationId);else if(e.type==='sleep')add(e.note,e.timestamp,'Observação do sono',e.id)}
  for(const m of meds)for(const n of (m.notes||[]))add(n.text,n.timestamp,'Anotação do medicamento',n.id,m.id);
  return out.sort((a,b)=>new Date(b.timestamp)-new Date(a.timestamp))
}
function learningMedicationWords(meds){const set=new Set();for(const m of meds){[m.activeIngredient,m.referenceName,m.lab,...(m.aliases||[])].filter(Boolean).forEach(v=>normalizeText(v).split(' ').forEach(w=>set.add(w)));for(const p of (m.presentations||[]))[p.brand,p.lab,p.form].filter(Boolean).forEach(v=>normalizeText(v).split(' ').forEach(w=>set.add(w)))}return set}
function learningQuestionPostponed(state,key){const until=state.postponed[key];return until&&Number(until)>Date.now()}
function learningExample(text,term){const clean=String(text||'').replace(/\s+/g,' ').trim();return clean.length>170?`${clean.slice(0,167)}…`:clean}

async function learningBuildQuestions(events=null,meds=null){events=events||await allEvents();meds=meds||await allMedications();const observations=await learningCollectObservations(events,meds),state=learningState(),medWords=learningMedicationWords(meds),baseSeen={},unknown={};
  for(const obs of observations){const norm=normalizeText(obs.text),concepts=learningConceptsInText(obs.text);
    for(const [term,data] of Object.entries(LEARNING_BASE_LOOKUP)){if(!learningContainsPhrase(norm,term)||learningPhraseNegated(norm,term))continue;const key=`confirm|${term}|${data.concept}`;(baseSeen[key]??={type:'confirm',key,term,display:data.display,concept:data.concept,count:0,examples:[]}).count++;if(baseSeen[key].examples.length<2)baseSeen[key].examples.push({text:learningExample(obs.text,term),source:obs.source})}
    const tokens=[...new Set(norm.split(' ').filter(Boolean))];
    for(const term of tokens){if((term.length<4&&term!=='mal'&&term!=='bem')||LEARNING_STOPWORDS.has(term)||medWords.has(term)||LEARNING_BASE_LOOKUP[term]||state.terms[term]||state.ignored[term]||/^\d+$/.test(term))continue;const st=unknown[term]??={type:'unknown',term,display:term,count:0,examples:[],conceptScores:{}};st.count++;if(st.examples.length<2)st.examples.push({text:learningExample(obs.text,term),source:obs.source});for(const c of concepts)st.conceptScores[c.concept]=(st.conceptScores[c.concept]||0)+1;unknown[term]=st}
  }
  const questions=[];
  Object.values(baseSeen).sort((a,b)=>b.count-a.count).forEach(q=>{if(questions.length>=3)return;if(state.terms[q.term]||state.ignored[q.term]||state.rejected[`${q.term}|${q.concept}`]||learningQuestionPostponed(state,q.key))return;questions.push(q)});
  Object.values(unknown).sort((a,b)=>b.count-a.count).forEach(st=>{if(questions.length>=8)return;const ranked=Object.entries(st.conceptScores).sort((a,b)=>b[1]-a[1]),top=ranked[0],second=ranked[1];if(top&&top[1]>=2&&(!second||top[1]>second[1])){const key=`infer|${st.term}|${top[0]}`;if(state.rejected[`${st.term}|${top[0]}`]||learningQuestionPostponed(state,key))return;questions.push({...st,type:'infer',key,concept:top[0]})}else if(st.count>=3){const key=`classify|${st.term}`;if(learningQuestionPostponed(state,key))return;questions.push({...st,type:'classify',key})}});
  return{observations,questions}
}

function learningConceptButtons(term,key){return`<div class="learning-concepts">${Object.entries(LEARNING_CONCEPTS).map(([concept,label])=>`<button type="button" class="learning-chip" data-learning-action="map" data-learning-term="${esc(term)}" data-learning-concept="${concept}" data-learning-key="${esc(key)}">${esc(label)}</button>`).join('')}</div>`}
function learningQuestionHTML(q){const example=q.examples?.[0]?`<div class="learning-context"><small>${esc(q.examples[0].source)}</small><p>“${esc(q.examples[0].text)}”</p></div>`:'';
  if(q.type==='confirm')return`<article class="learning-question"><span class="learning-confidence high">SIGNIFICADO CONHECIDO</span><h3>Quando você usa “${esc(q.display)}”, devo interpretar como <b>${esc(learningConceptLabel(q.concept))}</b>?</h3><p>Encontrei esse termo ${q.count} vez(es) nos seus registros.</p>${example}<div class="learning-actions"><button type="button" class="primary-button" data-learning-action="yes" data-learning-term="${esc(q.term)}" data-learning-concept="${q.concept}" data-learning-key="${esc(q.key)}">Sim</button><button type="button" class="secondary-button" data-learning-action="no" data-learning-term="${esc(q.term)}" data-learning-concept="${q.concept}" data-learning-key="${esc(q.key)}">Não</button><button type="button" class="secondary-button" data-learning-action="later" data-learning-term="${esc(q.term)}" data-learning-key="${esc(q.key)}">Não sei</button></div></article>`;
  if(q.type==='infer')return`<article class="learning-question"><span class="learning-confidence medium">HIPÓTESE DO APP</span><h3>“${esc(q.display)}” parece estar relacionado a <b>${esc(learningConceptLabel(q.concept))}</b>. Faz sentido para você?</h3><p>Essa hipótese surgiu porque o termo se repetiu perto de expressões que o app já conhece.</p>${example}<div class="learning-actions"><button type="button" class="primary-button" data-learning-action="yes" data-learning-term="${esc(q.term)}" data-learning-concept="${q.concept}" data-learning-key="${esc(q.key)}">Sim</button><button type="button" class="secondary-button" data-learning-action="no" data-learning-term="${esc(q.term)}" data-learning-concept="${q.concept}" data-learning-key="${esc(q.key)}">Não</button><button type="button" class="secondary-button" data-learning-action="later" data-learning-term="${esc(q.term)}" data-learning-key="${esc(q.key)}">Não sei</button></div><details class="learning-other"><summary>Escolher outro significado</summary>${learningConceptButtons(q.term,q.key)}<button type="button" class="learning-chip muted" data-learning-action="ignore" data-learning-term="${esc(q.term)}" data-learning-key="${esc(q.key)}">Não é relevante</button></details></article>`;
  return`<article class="learning-question"><span class="learning-confidence low">TERMO NOVO</span><h3>Você usou “${esc(q.display)}” ${q.count} vezes. O que esse termo costuma significar para você?</h3>${example}${learningConceptButtons(q.term,q.key)}<div class="learning-actions"><button type="button" class="secondary-button" data-learning-action="ignore" data-learning-term="${esc(q.term)}" data-learning-key="${esc(q.key)}">Não é relevante</button><button type="button" class="secondary-button" data-learning-action="later" data-learning-term="${esc(q.term)}" data-learning-key="${esc(q.key)}">Não sei agora</button></div></article>`
}

function learningEnsureUI(){if(document.querySelector('[data-view="learning"]'))return;const settingsView=document.querySelector('[data-view="settings"]'),content=document.getElementById('content');if(!content||!settingsView)return;const view=document.createElement('section');view.className='view';view.dataset.view='learning';view.innerHTML=`<header class="page-header"><div><p class="eyebrow">Ensine como você se expressa</p><h1>Aprendizado</h1></div></header><div class="notice-card learning-notice"><span class="notice-icon" data-icon="spark"></span><div><strong>Aprendizado local</strong><p>O app lê os textos dos seus registros, cria hipóteses e pergunta quando tem dúvida. Suas respostas ficam neste aparelho e ajudam as próximas análises.</p></div></div><section class="analysis-card"><p class="section-kicker">MOTOR LOCAL</p><h2>O que ele está aprendendo</h2><div class="metric-grid" id="learningMetrics"></div></section><section class="learning-section"><div class="section-title-row"><div><p class="section-kicker">PERGUNTAS</p><h2>Ajude o app a entender você</h2></div></div><div id="learningQuestions"></div></section><section class="learning-section"><div class="section-title-row"><div><p class="section-kicker">MEMÓRIA</p><h2>Vocabulário pessoal</h2></div></div><div class="analysis-card" id="learningVocabulary"></div></section><section class="analysis-card learning-explain"><h2>Como isso funciona</h2><p>O app não inventa diagnósticos. Ele reconhece conceitos, respeita negações simples, observa quando expressões aparecem próximas e cruza isso com horários de medicamentos e sono. Quando não tem confiança, pergunta.</p></section>`;content.insertBefore(view,settingsView);
  const bar=document.querySelector('.tab-bar'),settingsTab=bar?.querySelector('[data-tab="settings"]');if(bar&&settingsTab){const button=document.createElement('button');button.className='tab-item';button.dataset.tab='learning';button.innerHTML='<span data-icon="spark"></span><small>Aprendizado</small>';bar.insertBefore(button,settingsTab)}
  if(!document.getElementById('learning-style')){const st=document.createElement('style');st.id='learning-style';st.textContent='.learning-section{margin:22px 0}.learning-notice{margin-bottom:18px}.learning-question{background:var(--card-bg,#fff);border:1px solid var(--line,#e6e6ea);border-radius:22px;padding:16px;margin:10px 0;box-shadow:0 8px 24px rgba(0,0,0,.04)}.learning-question h3{font-size:16px;line-height:1.35;margin:8px 0 6px}.learning-question>p{font-size:13px;opacity:.7;margin:0 0 10px}.learning-confidence{display:inline-flex;font-size:9px;font-weight:750;letter-spacing:.08em;padding:5px 8px;border-radius:999px;background:rgba(116,167,255,.15)}.learning-confidence.medium{background:rgba(255,174,66,.15)}.learning-confidence.low{background:rgba(140,140,145,.12)}.learning-context{padding:10px 12px;border-radius:14px;background:rgba(120,120,128,.08);margin:10px 0}.learning-context small{font-size:10px;font-weight:700;opacity:.6}.learning-context p{font-size:13px;line-height:1.45;margin:4px 0 0}.learning-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.learning-actions button{flex:1;min-width:82px}.learning-concepts{display:flex;gap:7px;flex-wrap:wrap;margin:12px 0}.learning-chip{border:0;border-radius:999px;padding:8px 10px;background:rgba(116,167,255,.13);color:inherit;font:inherit;font-size:12px;font-weight:650}.learning-chip.muted{background:rgba(120,120,128,.1)}.learning-other{margin-top:10px}.learning-other summary{font-size:12px;font-weight:650;cursor:pointer}.learning-vocab-row{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:11px 0;border-bottom:1px solid rgba(120,120,128,.12)}.learning-vocab-row:last-child{border-bottom:0}.learning-vocab-row span{display:flex;flex-direction:column;gap:3px}.learning-vocab-row small{opacity:.6}.learning-remove{border:0;background:rgba(120,120,128,.1);border-radius:999px;padding:7px 10px;color:inherit}.learning-empty{font-size:13px;opacity:.65;padding:8px 0}.learning-explain p{font-size:13px;line-height:1.55;opacity:.75}';document.head.appendChild(st)}
  hydrateIcons(view);hydrateIcons(bar);if(typeof applyRegistroTabBar==='function')applyRegistroTabBar()
}

async function renderLearning(){learningEnsureUI();if(!db)return;const events=await allEvents(),meds=await allMedications(),{observations,questions}=await learningBuildQuestions(events,meds),state=learningState(),metrics=document.getElementById('learningMetrics'),box=document.getElementById('learningQuestions'),vocab=document.getElementById('learningVocabulary');if(!metrics||!box||!vocab)return;
  metrics.innerHTML=[metric(String(observations.length),'Trechos analisados'),metric(String(Object.keys(state.terms).length),'Termos aprendidos'),metric(String(questions.length),'Perguntas pendentes'),metric('Local','Processamento')].join('');
  box.innerHTML=questions.length?questions.map(learningQuestionHTML).join(''):'<div class="analysis-card"><div class="learning-empty">Nenhuma dúvida importante agora. O app continuará observando novos textos e perguntará quando encontrar algo que valha confirmar.</div></div>';
  const entries=Object.entries(state.terms).sort((a,b)=>(b[1].updatedAt||'').localeCompare(a[1].updatedAt||''));vocab.innerHTML=entries.length?entries.map(([term,data])=>`<div class="learning-vocab-row"><span><strong>${esc(data.display||term)}</strong><small>${esc(learningConceptLabel(data.concept))} · ${data.source==='confirmed'?'confirmado por você':'aprendido com você'}</small></span><button type="button" class="learning-remove" data-learning-action="remove" data-learning-term="${esc(term)}">Remover</button></div>`).join(''):`<div class="learning-empty">Ainda não há termos pessoais aprendidos. As confirmações que você fizer aparecerão aqui.</div>`;
  box.querySelectorAll('[data-learning-action]').forEach(b=>b.onclick=()=>learningHandleAction(b));vocab.querySelectorAll('[data-learning-action]').forEach(b=>b.onclick=()=>learningHandleAction(b))
}

async function learningHandleAction(button){const action=button.dataset.learningAction,term=normalizeText(button.dataset.learningTerm||''),concept=button.dataset.learningConcept,key=button.dataset.learningKey||`term|${term}`,state=learningState();if(!term)return;
  if(action==='yes'||action==='map'){state.terms[term]={display:button.dataset.learningTerm||term,concept,source:action==='yes'&&LEARNING_BASE_LOOKUP[term]?'confirmed':'learned',updatedAt:new Date().toISOString()};delete state.ignored[term];delete state.rejected[`${term}|${concept}`];delete state.postponed[key]}
  else if(action==='no'){state.rejected[`${term}|${concept}`]={updatedAt:new Date().toISOString()};delete state.postponed[key]}
  else if(action==='later'){state.postponed[key]=Date.now()+7*86400000}
  else if(action==='ignore'){state.ignored[term]={display:button.dataset.learningTerm||term,updatedAt:new Date().toISOString()};delete state.terms[term];delete state.postponed[key]}
  else if(action==='remove'){delete state.terms[term]}
  learningSaveState(state);await renderAll();if(action==='later')toast('Pergunta adiada.');else if(action==='no')toast('Entendido. Não vou usar essa associação.');else if(action==='ignore')toast('Termo marcado como não relevante.');else if(action==='remove')toast('Termo removido do vocabulário pessoal.');else toast('Aprendizado salvo.')
}

/* A aba Análises passa a considerar todos os textos observacionais relevantes. */
renderAnalysis=async function(events){const sorted=[...events].sort((a,b)=>new Date(b.timestamp)-new Date(a.timestamp)),meds=await allMedications(),observations=await learningCollectObservations(sorted,meds),cycle=currentCycle(sorted),latestObs=observations[0],cycleMeds=sorted.filter(e=>e.type==='medication'&&new Date(e.timestamp).getTime()>=cycle.start),contextStart=cycle.start-24*3600000,contextMeds=cycle.lastSleep?sorted.filter(e=>e.type==='medication'&&new Date(e.timestamp).getTime()<cycle.start&&new Date(e.timestamp).getTime()>=contextStart):[],lastSleep=cycle.lastSleep||sorted.find(e=>e.type==='sleep');document.getElementById('currentAnalysis').innerHTML=[analysisRow('Período considerado',cycle.label),analysisRow('Último relato',latestObs?`“${latestObs.text.length>120?latestObs.text.slice(0,117)+'…':latestObs.text}” · ${latestObs.source} · ${humanAgo(latestObs.timestamp)}`:'Ainda não há textos observacionais.'),analysisRow(cycle.lastSleep?'Medicamentos desde que acordou':'Medicamentos recentes',cycleMeds.length?cycleMeds.map(medicationEventLabel).join(' · '):'Nenhum registro nesse período.'),...(contextMeds.length?[analysisRow('Contexto antes do último sono',contextMeds.map(medicationEventLabel).join(' · '))]:[]),analysisRow('Sono mais recente',lastSleep?`${durationLabel(durationHours(lastSleep.startTime,lastSleep.endTime))}${lastSleep.quality?` · qualidade ${lastSleep.quality}`:''}`:'Ainda não há registros de sono.')].join('');
  const admins=sorted.filter(e=>e.type==='medication'),grouped={};for(const a of admins){const key=a.medication||'Medicamento';if(!grouped[key])grouped[key]={count:0,concepts:[],sources:{}};const st=new Date(a.timestamp).getTime(),en=st+8*3600000,nearby=observations.filter(o=>{const t=new Date(o.timestamp).getTime();return t>=st&&t<=en});grouped[key].count+=nearby.length;for(const o of nearby){grouped[key].sources[o.source]=(grouped[key].sources[o.source]||0)+1;for(const c of learningConceptsInText(o.text))grouped[key].concepts.push(c.concept)}}const assoc=Object.entries(grouped).sort((a,b)=>b[1].count-a[1].count).slice(0,4);document.getElementById('associationAnalysis').innerHTML=assoc.length?assoc.map(([name,data])=>{const c={};data.concepts.forEach(t=>c[t]=(c[t]||0)+1);const common=Object.entries(c).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([t,n])=>`${learningConceptLabel(t)} (${n})`).join(', ');const src=Object.entries(data.sources).sort((a,b)=>b[1]-a[1]).slice(0,2).map(([s,n])=>`${s}: ${n}`).join(' · ');return analysisRow(name,`${data.count} relato(s) até 8h depois das administrações${common?`. Conceitos recorrentes: ${common}`:''}${src?`. Fontes: ${src}`:''}.`) }).join(''):analysisRow('Ainda sem padrão','Registre administrações e textos ao longo do tempo.');
  const sleeps=sorted.filter(e=>e.type==='sleep'),avg=sleeps.length?sleeps.reduce((s,e)=>s+durationHours(e.startTime,e.endTime),0)/sleeps.length:null,qs=sleeps.filter(e=>Number(e.quality)),avgQ=qs.length?qs.reduce((s,e)=>s+Number(e.quality),0)/qs.length:null;document.getElementById('sleepAnalysis').innerHTML=[metric(avg==null?'—':durationLabel(avg),'Média de duração'),metric(avgQ==null?'—':avgQ.toFixed(1),'Qualidade média'),metric(String(sleeps.length),'Noites registradas'),metric(sleeps[0]?durationLabel(durationHours(sleeps[0].startTime,sleeps[0].endTime)):'—','Último sono')].join('');
  const medRows=[];for(const m of meds){const c=medicationCostSummary(m,sorted);if(c)medRows.push(analysisRow(m.activeIngredient,`Último custo: ${c.unit!=null?`${money(c.unit)}/unidade`:'sem unidades definidas'}${c.monthly!=null?` · gasto registrado nos últimos 30 dias ≈ ${money(c.monthly)}`:''}`))}document.getElementById('medicationAnalysis').innerHTML=medRows.length?medRows.slice(0,6).join(''):analysisRow('Cadastre apresentações','Com unidades por caixa, compras e administrações o app calcula custo e duração.');
  const buys=sorted.filter(e=>e.type==='purchase'),groups={};for(const p of buys){const n=parseMoney(p.price);if(n==null)continue;(groups[p.medication||'Medicamento']??=[]).push(n)}const priceRows=Object.entries(groups).slice(0,5);document.getElementById('purchaseAnalysis').innerHTML=priceRows.length?priceRows.map(([name,vals])=>analysisRow(name,`${vals.length} compra(s) · média ${money(vals.reduce((a,b)=>a+b,0)/vals.length)} · menor ${money(Math.min(...vals))} · maior ${money(Math.max(...vals))}`)).join(''):analysisRow('Ainda sem histórico de preço','Registre compras com valor para comparar preços.')
};

const learningOriginalRenderAll=renderAll;renderAll=async function(){await learningOriginalRenderAll();await renderLearning()};
function learningBoot(){learningEnsureUI();hydrateIcons();if(typeof applyRegistroTabBar==='function')applyRegistroTabBar();if(db)renderAll();else setTimeout(learningBoot,180)}
learningBoot();
