async function handleShortcutImport(){const p=new URLSearchParams(location.search);if(!p.has('sleepStart')||!p.has('sleepEnd'))return;const start=new Date(p.get('sleepStart')),end=new Date(p.get('sleepEnd'));if(!(start<end))return;const payload={start:start.toISOString(),end:end.toISOString(),quality:Number(p.get('sleepQuality')||4),note:p.get('sleepNote')||''},existing=(await allEvents()).some(e=>e.type==='sleep'&&e.startTime===payload.start&&e.endTime===payload.end);history.replaceState({},'',location.pathname);if(existing)return toast('Esse período de sono já está registrado.');const mode=getSettings().healthImportMode;if(mode==='auto'){await putEvent({id:uid('sleep-health'),type:'sleep',timestamp:payload.end,startTime:payload.start,endTime:payload.end,quality:payload.quality,note:payload.note,source:'health-shortcut',demo:false});localStorage.setItem(LAST_HEALTH_IMPORT_KEY,new Date().toISOString());toast('Sono importado.')}else if(mode==='ask'){if(confirm('Salvar o sono recebido automaticamente? Toque em Cancelar para revisar.')){await putEvent({id:uid('sleep-health'),type:'sleep',timestamp:payload.end,startTime:payload.start,endTime:payload.end,quality:payload.quality,note:payload.note,source:'health-shortcut',demo:false});localStorage.setItem(LAST_HEALTH_IMPORT_KEY,new Date().toISOString());toast('Sono importado.')}else openSleepSheet(payload)}else openSleepSheet(payload)}

function switchTab(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===name));document.querySelectorAll('.tab-item').forEach(b=>b.classList.toggle('selected',b.dataset.tab===name));updateTabBubble();window.scrollTo({top:0,behavior:'instant'})}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2300)}

function openType(type){if(type==='note')openNoteSheet();else if(type==='medication')openMedicationSheet();else if(type==='purchase')openPurchaseSheet();else if(type==='sleep')openSleepSheet()}

document.addEventListener('click',e=>{const action=e.target.closest('[data-type]');if(action)openType(action.dataset.type);const menu=e.target.closest('[data-menu]');if(menu)openEventMenu(menu.dataset.menu);const tab=e.target.closest('[data-tab]');if(tab)switchTab(tab.dataset.tab);const go=e.target.closest('[data-go]');if(go)switchTab(go.dataset.go);const filter=e.target.closest('[data-filter]');if(filter){historyFilter=filter.dataset.filter;document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('selected',b===filter));renderAll()}const theme=e.target.closest('[data-theme-value]');if(theme)setSetting('theme',theme.dataset.themeValue);const accent=e.target.closest('[data-accent]');if(accent)setSetting('accent',accent.dataset.accent);const size=e.target.closest('[data-icon-size]');if(size)setSetting('iconSize',size.dataset.iconSize);const iw=e.target.closest('[data-icon-weight]');if(iw)setSetting('iconWeight',iw.dataset.iconWeight);const ff=e.target.closest('[data-font-family]');if(ff)setSetting('fontFamily',ff.dataset.fontFamily);const fw=e.target.closest('[data-font-weight]');if(fw)setSetting('fontWeight',fw.dataset.fontWeight);const hm=e.target.closest('[data-health-mode]');if(hm)setSetting('healthImportMode',hm.dataset.healthMode)});

document.getElementById('closeBtn').onclick=closeSheet;document.getElementById('backdrop').onclick=e=>{if(e.target.id==='backdrop')closeSheet()};document.getElementById('homeOptionsBtn').onclick=()=>switchTab('settings');document.getElementById('exportBtn').onclick=exportData;document.getElementById('importBtn').onclick=()=>document.getElementById('importFile').click();document.getElementById('importFile').onchange=e=>{const f=e.target.files?.[0];if(f)importData(f);e.target.value=''};document.getElementById('svgImportFile').onchange=async e=>{const f=e.target.files?.[0];if(f&&iconEditorTarget){const text=await f.text();openIconEditor(iconEditorTarget);document.getElementById('svgIconText').value=text;document.getElementById('bankIconCode').value='';document.getElementById('iconPreview').innerHTML=`<svg class="svg-icon" viewBox="0 0 24 24">${sanitizeSvgMarkup(text)}</svg>`}e.target.value=''};document.getElementById('healthImportInfoBtn').onclick=healthImportInfo;document.getElementById('medicationRegistryBtn').onclick=openMedicationRegistry;document.getElementById('customIconsBtn').onclick=openCustomIcons;document.getElementById('tabbarLabBtn').onclick=()=>location.href='./tabbar-lab.html';document.getElementById('restoreDemoBtn').onclick=restoreDemo;document.getElementById('clearBtn').onclick=clearData;document.getElementById('showVersionToggle').onclick=()=>setSetting('showVersion',!getSettings().showVersion);document.getElementById('hideTabLabelsToggle').onclick=()=>setSetting('hideTabLabels',!getSettings().hideTabLabels);document.getElementById('versionLabel').textContent=APP_VERSION;

(async()=>{applySettings();db=await openDB();await ensureRichDemoData();await seedDemo();await ensureProfiles();await handleShortcutImport();await renderAll();if('serviceWorker'in navigator)navigator.serviceWorker.register(`./sw.js?v=${APP_VERSION}`).catch(console.error)})();