async function renderHome(events){const today=localDate(new Date()),day=events.filter(e=>eventDay(e)===today).sort((a,b)=>new Date(b.timestamp)-new Date(a.timestamp)),notes=day.filter(e=>e.type==='note'),meds=day.filter(e=>e.type==='medication'),sleeps=day.filter(e=>e.type==='sleep'),buys=day.filter(e=>e.type==='purchase');document.getElementById('dateLabel').textContent=`Hoje · ${new Date().toLocaleDateString('pt-BR',{day:'2-digit',month:'short'})}`;let sleep='Nenhum';if(sleeps[0])sleep=`${durationLabel(durationHours(sleeps[0].startTime,sleeps[0].endTime))}${sleeps[0].quality?` · <span class="quality-inline"><span class="quality-dot ${qualityColorClass(sleeps[0].quality)}"></span>${sleeps[0].quality}</span>`:''}`;document.getElementById('summaryList').innerHTML=[summaryRow('note','Anotações',String(notes.length)),summaryRow('pill','Medicamentos',String(meds.length)),summaryRow('moon','Sono',sleep),summaryRow('bag','Compras',String(buys.length))].join('');const recent=day.slice(0,5),box=document.getElementById('homeTimeline');box.innerHTML=recent.map(eventCard).join('');document.getElementById('homeEmpty').classList.toggle('hidden',recent.length>0);await hydrateAudio(box)}
async function renderHistory(events){const filtered=events.filter(e=>historyFilter==='all'||e.type===historyFilter).sort((a,b)=>new Date(b.timestamp)-new Date(a.timestamp)),container=document.getElementById('historyList');container.innerHTML='';let current='';for(const e of filtered){const d=eventDay(e);if(d!==current){current=d;container.insertAdjacentHTML('beforeend',`<div class="history-day">${dayLabel(d)}</div>`)}container.insertAdjacentHTML('beforeend',eventCard(e))}document.getElementById('historyEmpty').classList.toggle('hidden',filtered.length>0);await hydrateAudio(container)}
function analysisRow(title,text){return`<div class="analysis-row"><strong>${esc(title)}</strong><span>${esc(text)}</span></div>`}
function metric(value,label){return`<div class="metric"><strong>${esc(value)}</strong><span>${esc(label)}</span></div>`}
function moodTerms(text=''){const t=normalizeText(text),terms=['calmo','tranquilo','bem','feliz','ansioso','ansiedade','irritado','triste','agitado','cansado','sonolento','insonia','foco','concentrado','dor de cabeca','nausea','tontura'];return terms.filter(term=>t.includes(normalizeText(term)))}

function currentCycle(events){const sleeps=events.filter(e=>e.type==='sleep'&&e.endTime&&new Date(e.endTime)<=new Date()).sort((a,b)=>new Date(b.endTime)-new Date(a.endTime)),lastSleep=sleeps[0];if(lastSleep){const wake=new Date(lastSleep.endTime).getTime();return{start:wake,label:`Desde o último despertar (${timeLabel(lastSleep.endTime)})`,lastSleep}}return{start:Date.now()-24*3600000,label:'Últimas 24h',lastSleep:null}}
function medicationEventLabel(e){return`${e.medication||'Medicamento'}${e.dose?` ${e.dose}`:''} · ${timeLabel(e.timestamp)}`}

function buildPackageLots(m,events){const purchases=events.filter(e=>e.type==='purchase'&&medMatchesEvent(m,e)).sort((a,b)=>new Date(a.timestamp)-new Date(b.timestamp)),admins=events.filter(e=>e.type==='medication'&&medMatchesEvent(m,e)).sort((a,b)=>new Date(a.timestamp)-new Date(b.timestamp));const lots=[];for(const p of purchases){const pres=findPresentation(m,p.presentationId);const packages=Math.max(1,Math.round(Number(p.packages)||1));const unitsPerPackage=Number(p.unitsPerPackage)||Number(pres?.unitsPerPackage)||0;const totalPrice=parseMoney(p.price);if(!unitsPerPackage)continue;for(let i=0;i<packages;i++)lots.push({purchaseId:p.id,presentationId:p.presentationId,start:new Date(p.timestamp).getTime(),units:unitsPerPackage,remaining:unitsPerPackage,price:totalPrice==null?null:totalPrice/packages,finishedAt:null,label:pres?presentationDisplay(pres):eSafe(p.medication)})}for(const a of admins){let need=Number(a.unitsTaken)||1;let t=new Date(a.timestamp).getTime();for(const lot of lots){if(need<=0)break;if(t<lot.start||lot.remaining<=0)continue;const used=Math.min(need,lot.remaining);lot.remaining-=used;need-=used;if(lot.remaining<=0&&!lot.finishedAt)lot.finishedAt=t}}return lots}
function eSafe(v){return String(v||'')}
function medicationCostSummary(m,events){const lots=buildPackageLots(m,events),latest=[...lots].sort((a,b)=>b.start-a.start)[0];if(!latest)return null;const pres=findPresentation(m,latest.presentationId),unit=latest.price==null?null:latest.price/latest.units,blister=unit!=null&&Number(pres?.unitsPerBlister)?unit*Number(pres.unitsPerBlister):null;const since=Date.now()-30*86400000,used30=events.filter(e=>e.type==='medication'&&medMatchesEvent(m,e)&&new Date(e.timestamp).getTime()>=since).reduce((s,e)=>s+(Number(e.unitsTaken)||1),0),monthly=unit==null?null:unit*used30;return{latest,unit,blister,monthly,lots}}
