/* Redesign visual global + escalas emocionais simplificadas (humor 0–5, dimensões 0–4). */
const RM_VISUAL_VERSION='1.0.0';
const RM_MOOD_PALETTE={
  0:{color:'#17171D',border:'#7657FF',text:'#F7F5FF',glow:'rgba(118,87,255,.52)'},
  1:{color:'#FF3B30',border:'#FF766D',text:'#FFFFFF',glow:'rgba(255,59,48,.42)'},
  2:{color:'#FF6A00',border:'#FFA05C',text:'#FFFFFF',glow:'rgba(255,106,0,.40)'},
  3:{color:'#FFD60A',border:'#FFF079',text:'#3A2B00',glow:'rgba(255,214,10,.38)'},
  4:{color:'#35D98B',border:'#8CF0BD',text:'#073321',glow:'rgba(53,217,139,.40)'},
  5:{color:'#56C8FF',border:'#C6F1FF',text:'#06283D',glow:'rgba(86,200,255,.58)'}
};
const RM_DIMENSION_COLORS={
  anxiety:'#F07800',happiness:'#46C936',energy:'#00AEEA',irritability:'#F04455',activation:'#E83FC5',sadness:'#5266EE',concentration:'#00A7A5',sleepiness:'#895EEA'
};
function rmClamp(n,min,max){return Math.max(min,Math.min(max,Number(n)))}
function rmMood(score){return RM_MOOD_PALETTE[Math.round(rmClamp(score,0,5))]||RM_MOOD_PALETTE[0]}
function rmHashHue(text=''){let h=0;for(const ch of String(text))h=(h*31+ch.charCodeAt(0))%360;return h}
function rmDimensionColor(d){if(!d)return'#7259D6';return RM_DIMENSION_COLORS[d.id]||`hsl(${rmHashHue(d.id||d.label)} 76% 52%)`}

/* Migração reversível: preserva os valores antigos em campos legacy antes de converter. */
async function rmMigrateScales(){
  const s=getSettings();if(s.rmScaleMigration==='0-5_0-4_v1')return false;
  const events=await allEvents();let changed=false;
  for(const e of events){if(e?.type!=='note')continue;let next={...e},touch=false;
    if(e.moodScore!==null&&e.moodScore!==undefined&&e.moodScore!==''&&Number.isFinite(Number(e.moodScore))){
      const old=Number(e.moodScore);next.moodScoreLegacy10=old;next.moodScore=rmClamp(Math.round(old/2),0,5);next.moodScaleModel='0-5';touch=true;
    }
    if(e.emotionScores&&typeof e.emotionScores==='object'){
      next.emotionScoresLegacy5={...e.emotionScores};next.emotionScores={};
      for(const [k,v] of Object.entries(e.emotionScores))next.emotionScores[k]=rmClamp(Math.round(Number(v)*4/5),0,4);
      next.emotionIntensityModel='0-4';touch=true;
    }
    if(touch){await putEvent(next);changed=true}
  }
  s.rmScaleMigration='0-5_0-4_v1';s.moodScaleModel='0-5';s.emotionIntensityModel='0-4';saveSettings(s);return changed
}

/* Componentes de preenchimento. */
emotionMoodSelectorHTML=function(value=null){return`<div class="mood-block rm-mood-block"><div class="mood-scale-labels"><span>0 · extremamente mal</span><span>3 · neutro</span><span>5 · estado ideal</span></div><div class="mood-scale">${Array.from({length:6},(_,n)=>{const c=rmMood(n);return`<button type="button" class="mood-score ${n===0?'rm-zero ':''}${n===5?'rm-five ':''}${value!==null&&value!==undefined&&Number(value)===n?'selected':''}" data-mood-score="${n}" style="--mood-color:${c.color};--mood-border:${c.border};--mood-text:${c.text};--mood-glow:${c.glow}">${n}</button>`}).join('')}</div><button type="button" class="tiny-clear" id="clearMoodScore">Limpar nota</button></div>`};

emotionDimensionHTML=function(d,value=null){const color=rmDimensionColor(d);return`<div class="emotion-dimension" data-emotion-dimension="${esc(d.id)}" style="--dimension-color:${color}"><div class="emotion-dimension-head"><strong>${esc(d.label)}</strong><button type="button" class="tiny-clear" data-clear-dimension="${esc(d.id)}">Limpar</button></div><div class="emotion-scale">${[0,1,2,3,4].map(n=>`<button type="button" data-emotion-score="${n}" class="${value!==null&&value!==undefined&&Number(value)===n?'selected':''}">${n}</button>`).join('')}</div><div class="emotion-scale-caption"><span>0 · ${esc(d.low||'ausente')}</span><span>4 · ${esc(d.high||'muito intensa')}</span></div></div>`};

emotionAdvancedHTML=function(values={}){const dims=emotionDimensions().filter(d=>d.active!==false);return`<details class="emotion-advanced" id="emotionAdvanced"><summary>Detalhar emoções e sensações</summary><p class="helper">Opcional. Cada dimensão usa sua própria cor; a intensidade vai de 0 (ausente/baixa) a 4 (muito intensa/alta).</p><div id="emotionDimensionsList">${dims.map(d=>emotionDimensionHTML(d,values[d.id])).join('')}</div><button type="button" class="secondary-button full-button" id="addEmotionDimensionBtn">+ Criar nova dimensão</button><div class="emotion-new-dimension hidden" id="emotionNewDimension"><div class="field"><label>Nome da dimensão</label><input id="emotionDimensionName" placeholder="Ex.: despersonalização"></div><div class="field-grid"><div class="field"><label>0 significa</label><input id="emotionDimensionLow" placeholder="ausente"></div><div class="field"><label>4 significa</label><input id="emotionDimensionHigh" placeholder="muito intensa"></div></div><div class="learning-actions"><button type="button" class="primary-button" id="saveEmotionDimensionBtn">Adicionar</button><button type="button" class="secondary-button" id="cancelEmotionDimensionBtn">Cancelar</button></div></div></details>`};

/* Textos da linha do tempo e detalhes passam a refletir as novas escalas. */
const rmPreviousKindInfo=kindInfo;
kindInfo=function(e){if(e?.type!=='note')return rmPreviousKindInfo(e);const meta=[];if(e.moodScore!=null)meta.push(`Estado ${e.moodScore}/5`);if(e.tag)meta.push(e.tag);for(const [id,v] of Object.entries(e.emotionScores||{}).slice(0,2))meta.push(`${e.emotionLabels?.[id]||emotionDimensions().find(d=>d.id===id)?.label||id} ${v}/4`);return{kind:e.audioOnly?'ANOTAÇÃO DE VOZ':(!e.text&&e.moodScore!=null?'CHECK-IN':'ANOTAÇÃO'),className:'note',title:e.text||(e.moodScore!=null?`Estado emocional ${e.moodScore}/5`:'Gravação de voz'),meta}};
const rmPreviousOpenEventViewer=openEventViewer;
openEventViewer=async function(id){const e=(await allEvents()).find(x=>x.id===id);if(e?.type!=='note')return rmPreviousOpenEventViewer(id);const rows=[registroDetailRow('Estado emocional',e.moodScore!=null?`${e.moodScore} de 5`:''),registroDetailRow('Anotação',e.text||''),registroDetailRow('Tag',e.tag)];for(const [key,value] of Object.entries(e.emotionScores||{}))rows.push(registroDetailRow(e.emotionLabels?.[key]||emotionDimensions().find(d=>d.id===key)?.label||key,`${value} de 4`));rows.push(registroDetailRow('Data e horário',registroDetailDate(e.timestamp)));const audio=e.hasAudio?`<div class="analysis-row"><strong>Áudio</strong><span data-audio="${e.id}"></span></div>`:'';openBackdrop(e.text?'Anotação':'Check-in emocional',`<div class="analysis-stack">${rows.join('')}${audio}</div><div class="form-actions"><button type="button" class="secondary-button" id="viewerCloseBtn">Fechar</button><button type="button" class="primary-button" id="viewerEditBtn">Editar</button></div>`,ev=>ev.preventDefault());document.getElementById('viewerCloseBtn').onclick=closeSheet;document.getElementById('viewerEditBtn').onclick=()=>openEventEditor(id);if(e.hasAudio)await hydrateAudio(document.getElementById('form'))};

/* Gráficos emocionais com cor informativa, glow e área em degradê. */
let rmChartUid=0;
function rmLineChart(points,opts,mode,dimension=null){
  if(points.length<2)return chartEmpty('Ainda há poucos pontos para desenhar uma linha.');
  const W=720,H=270,pad={l:42,r:16,t:18,b:35},iw=W-pad.l-pad.r,ih=H-pad.t-pad.b,minY=mode==='mood'?0:0,maxY=mode==='mood'?5:4,x0=Math.min(...points.map(p=>p.x)),x1=Math.max(...points.map(p=>p.x)),span=Math.max(1,x1-x0),x=v=>pad.l+(v-x0)/span*iw,y=v=>pad.t+(maxY-v)/(maxY-minY)*ih,id=`rm${++rmChartUid}`,ticks=[minY,(minY+maxY)/2,maxY],path=points.map((p,i)=>`${i?'L':'M'}${x(p.x).toFixed(1)},${y(p.y).toFixed(1)}`).join(' '),base=`${path} L${x(points[points.length-1].x).toFixed(1)},${H-pad.b} L${x(points[0].x).toFixed(1)},${H-pad.b} Z`,dimColor=dimension?rmDimensionColor(dimension):null;
  const stops=mode==='mood'?points.map(p=>`<stop offset="${((p.x-x0)/span*100).toFixed(1)}%" stop-color="${rmMood(p.y).color}"/>`).join(''):`<stop offset="0%" stop-color="${dimColor}"/><stop offset="100%" stop-color="${dimColor}"/>`;
  const defs=`<defs><linearGradient id="${id}line" x1="0" y1="0" x2="1" y2="0">${stops}</linearGradient><linearGradient id="${id}fade" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#fff" stop-opacity=".7"/><stop offset="55%" stop-color="#fff" stop-opacity=".25"/><stop offset="100%" stop-color="#fff" stop-opacity="0"/></linearGradient><mask id="${id}mask"><rect width="100%" height="100%" fill="url(#${id}fade)"/></mask><filter id="${id}glow" x="-60%" y="-60%" width="220%" height="220%"><feGaussianBlur stdDeviation="5" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>`;
  const grid=`<g class="chart-grid">${ticks.map(t=>`<line x1="${pad.l}" y1="${y(t)}" x2="${W-pad.r}" y2="${y(t)}"/><text x="${pad.l-8}" y="${y(t)+4}" text-anchor="end">${mode==='mood'?`${Number(t).toFixed(t%1?1:0)}/5`:`${Number(t).toFixed(t%1?1:0)}/4`}</text>`).join('')}</g>`;
  const markers=(opts.markers||[]).map(m=>`<line class="chart-marker ${esc(m.kind||'')}" x1="${x(m.x)}" y1="${pad.t}" x2="${x(m.x)}" y2="${H-pad.b}"><title>${esc(m.title||'')}</title></line>`).join('');
  const dots=points.map(p=>{if(mode==='mood'){const c=rmMood(p.y),isZero=Number(p.y)===0,isFive=Number(p.y)===5,r=isFive?7:isZero?6:5.3;return`<circle cx="${x(p.x)}" cy="${y(p.y)}" r="${r+5}" fill="${isZero?'#7657FF':c.color}" opacity=".16" filter="url(#${id}glow)"/><circle cx="${x(p.x)}" cy="${y(p.y)}" r="${r}" fill="${c.color}" stroke="${isZero?'#7657FF':c.border}" stroke-width="${isFive?2.7:2}"><title>${esc(`${opts.xLabel?.(p)||p.label||''} · ${p.y}/5`)}</title></circle>${isFive?`<circle cx="${x(p.x)-1.6}" cy="${y(p.y)-2}" r="2" fill="rgba(255,255,255,.92)"/>`:''}`};const level=rmClamp(p.y,0,4),opacity=[.28,.42,.60,.80,1][level]||.7;return`<circle cx="${x(p.x)}" cy="${y(p.y)}" r="9" fill="${dimColor}" opacity="${opacity*.16}" filter="url(#${id}glow)"/><circle cx="${x(p.x)}" cy="${y(p.y)}" r="5.5" fill="${dimColor}" opacity="${opacity}" stroke="color-mix(in srgb,${dimColor} 70%,white 30%)" stroke-width="2"><title>${esc(`${opts.xLabel?.(p)||p.label||''} · ${p.y}/4`)}</title></circle>`}).join('');
  const areaColor=mode==='mood'?`url(#${id}line)`:dimColor;
  return`<svg class="local-chart-svg rm-emotion-chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(opts.yLabel||'')}">${defs}${grid}${markers}<path d="${base}" fill="${areaColor}" opacity="${mode==='mood'?'.22':'.14'}" mask="url(#${id}mask)"/><path class="chart-line" d="${path}" fill="none" stroke="url(#${id}line)" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>${dots}<text class="chart-axis-label" x="${pad.l}" y="${H-10}">${esc(opts.xLabel?.(points[0])||points[0].label||'')}</text><text class="chart-axis-label" x="${W-pad.r}" y="${H-10}" text-anchor="end">${esc(opts.xLabel?.(points[points.length-1])||points[points.length-1].label||'')}</text></svg>`
}
const rmPreviousLocalLineChart=localLineChart;
localLineChart=function(points,opts={}){if(opts?.yLabel==='Humor')return rmLineChart(points,{...opts,maxY:5,formatY:v=>`${Number(v).toFixed(0)}/5`},'mood');const dim=emotionDimensions().find(d=>d.label===opts?.yLabel);if(dim)return rmLineChart(points,{...opts,maxY:4,formatY:v=>`${Number(v).toFixed(0)}/4`},'dimension',dim);return rmPreviousLocalLineChart(points,opts)};

function rmMoodBarChart(rows){rows=rows.slice(0,6);if(!rows.length)return chartEmpty('Ainda não há dados suficientes.');const W=720,H=280,pad={l:44,r:16,t:18,b:54},iw=W-pad.l-pad.r,ih=H-pad.t-pad.b,max=Math.max(1,...rows.map(r=>r.value)),y=v=>pad.t+(max-v)/max*ih,zero=y(0),bw=Math.max(20,iw/rows.length*.58),id=`rmb${++rmChartUid}`;return`<svg class="local-chart-svg rm-mood-bars" viewBox="0 0 ${W} ${H}" role="img"><defs><filter id="${id}g" x="-50%" y="-50%" width="200%" height="200%"><feGaussianBlur stdDeviation="6" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter>${rows.map((r,i)=>{const c=rmMood(i);return`<linearGradient id="${id}${i}" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="${c.border}"/><stop offset="100%" stop-color="${c.color}"/></linearGradient>`}).join('')}</defs><line class="chart-zero" x1="${pad.l}" y1="${zero}" x2="${W-pad.r}" y2="${zero}"/>${rows.map((r,i)=>{const c=rmMood(i),cx=pad.l+(i+.5)*iw/rows.length,yy=y(r.value),h=Math.max(3,zero-yy),top=zero-h;return`<rect x="${cx-bw/2}" y="${top}" width="${bw}" height="${h}" rx="12" fill="${i===0?'#17171D':`url(#${id}${i})`}" stroke="${i===0?'#7657FF':c.border}" stroke-width="${i===5?2.5:1.5}"/><rect x="${cx-bw/2}" y="${top}" width="${bw}" height="${h}" rx="12" fill="${i===0?'#7657FF':c.color}" opacity=".10" filter="url(#${id}g)"/><text class="chart-bar-label" x="${cx}" y="${H-31}" text-anchor="middle">${i}</text><text class="chart-bar-value" x="${cx}" y="${Math.max(12,top-7)}" text-anchor="middle">${r.value}</text>`}).join('')}</svg>`}
const rmPreviousLocalBarChart=localBarChart;
localBarChart=function(rows,opts={}){const looksMood=rows?.length>=6&&rows.slice(0,6).every((r,i)=>String(r.label)===String(i));return looksMood?rmMoodBarChart(rows):rmPreviousLocalBarChart(rows,opts)};

function rmMoodScatterChart(points,opts={}){if(points.length<3)return chartEmpty('São necessários pelo menos 3 pares de dados para esse gráfico.');const W=720,H=280,pad={l:46,r:16,t:18,b:42},iw=W-pad.l-pad.r,ih=H-pad.t-pad.b,[autoMin,autoMax]=chartBounds(points.map(p=>p.x),0,1),minX=opts.xMin??autoMin,maxX=opts.xMax??autoMax,x=v=>pad.l+(v-minX)/Math.max(.0001,maxX-minX)*iw,y=v=>pad.t+(5-v)/5*ih,id=`rms${++rmChartUid}`;return`<svg class="local-chart-svg rm-mood-scatter" viewBox="0 0 ${W} ${H}" role="img"><defs><filter id="${id}g" x="-50%" y="-50%" width="200%" height="200%"><feGaussianBlur stdDeviation="5" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><g class="chart-grid">${[0,2.5,5].map(t=>`<line x1="${pad.l}" y1="${y(t)}" x2="${W-pad.r}" y2="${y(t)}"/><text x="${pad.l-8}" y="${y(t)+4}" text-anchor="end">${t%1?t.toFixed(1):t}/5</text>`).join('')}</g>${points.map(p=>{const c=rmMood(p.y),r=Number(p.y)===5?7:6;return`<circle cx="${x(p.x)}" cy="${y(p.y)}" r="${r+4}" fill="${Number(p.y)===0?'#7657FF':c.color}" opacity=".14" filter="url(#${id}g)"/><circle class="chart-scatter" cx="${x(p.x)}" cy="${y(p.y)}" r="${r}" fill="${c.color}" stroke="${Number(p.y)===0?'#7657FF':c.border}" stroke-width="2"><title>${esc(`${p.label||''} · ${opts.xFormat?.(p.x)||p.x} · ${p.y}/5`)}</title></circle>`}).join('')}<text class="chart-axis-label" x="${pad.l}" y="${H-12}">${esc(opts.xFormat?.(minX)||minX)}</text><text class="chart-axis-label" x="${W-pad.r}" y="${H-12}" text-anchor="end">${esc(opts.xFormat?.(maxX)||maxX)}</text></svg>`}
const rmPreviousLocalScatterChart=localScatterChart;
localScatterChart=function(points,opts={}){let isMood=false;try{isMood=Number(opts.yMax)===10&&String(opts.yFormat?.(3)||'').includes('/10')}catch{}return isMood?rmMoodScatterChart(points,{...opts,yMax:5,yFormat:v=>`${Number(v).toFixed(0)}/5`}):rmPreviousLocalScatterChart(points,opts)};

function rmFixAnalysisCopy(){const mood=document.querySelector('[data-analysis-item="chart-mood-line"] .chart-card-head div>p:last-child');if(mood)mood.textContent='Notas emocionais de 0 a 5 nos últimos 30 dias.';const dim=document.querySelector('[data-analysis-item="chart-dimension-line"] .chart-card-head div>p:last-child');if(dim)dim.textContent='Escolha uma dimensão para acompanhar sua evolução em escala de 0 a 4.'}
const rmPreviousRenderQuantitativeDashboard=renderQuantitativeDashboard;
renderQuantitativeDashboard=async function(events){await rmPreviousRenderQuantitativeDashboard(events);rmFixAnalysisCopy()};

/* Linguagem visual global: fundos em degradê, cartões luminosos, glow interno/externo e movimento suave. */
(function rmEnsureVisualStyles(){if(document.getElementById('rm-visual-system'))return;const st=document.createElement('style');st.id='rm-visual-system';st.textContent=`
:root{
 --rm-glass:rgba(255,255,255,.70);--rm-glass-2:rgba(248,249,255,.62);--rm-line:rgba(255,255,255,.80);
 --rm-shadow:0 16px 38px rgba(50,58,100,.10);--rm-shadow-soft:0 8px 24px rgba(50,58,100,.08);
 --rm-inner:inset 0 1px 0 rgba(255,255,255,.92);--rm-input:rgba(247,248,253,.76)
}
html[data-theme="dark"]{--rm-glass:rgba(28,29,36,.72);--rm-glass-2:rgba(22,23,30,.66);--rm-line:rgba(255,255,255,.10);--rm-shadow:0 18px 42px rgba(0,0,0,.34);--rm-shadow-soft:0 9px 26px rgba(0,0,0,.26);--rm-inner:inset 0 1px 0 rgba(255,255,255,.08);--rm-input:rgba(42,43,52,.74)}
body{background:radial-gradient(circle at 8% 4%,color-mix(in srgb,var(--record-note,var(--accent)) 11%,transparent),transparent 28%),radial-gradient(circle at 92% 12%,rgba(86,200,255,.12),transparent 34%),radial-gradient(circle at 62% 86%,rgba(118,87,255,.08),transparent 36%),linear-gradient(180deg,color-mix(in srgb,var(--bg) 94%,white 6%),var(--bg))!important;background-color:var(--bg)!important}
html[data-theme="dark"] body{background:radial-gradient(circle at 8% 4%,rgba(118,87,255,.15),transparent 28%),radial-gradient(circle at 92% 12%,rgba(35,168,255,.10),transparent 34%),radial-gradient(circle at 55% 86%,rgba(0,199,190,.07),transparent 36%),linear-gradient(180deg,#09090d,#000)!important}
.app-shell,.content{background:transparent!important}
.summary-card,.analysis-card,.settings-card,.notice-card,.action-card,.timeline-item,.empty-state,.registry-card,.learning-question,.presentation-row,.med-note-row,.package-row,.autocomplete-results{
 background:linear-gradient(145deg,var(--rm-glass),var(--rm-glass-2))!important;border:1px solid var(--rm-line)!important;box-shadow:var(--rm-inner),var(--rm-shadow)!important
}
.summary-card,.analysis-card,.settings-card,.notice-card,.action-card{backdrop-filter:blur(14px) saturate(140%);-webkit-backdrop-filter:blur(14px) saturate(140%)}
.analysis-card,.notice-card{box-shadow:var(--rm-inner),var(--rm-shadow),0 0 22px color-mix(in srgb,var(--accent) 5%,transparent)!important}
.primary-action{--rm-card-accent:var(--record-note,var(--accent));background:radial-gradient(circle at 18% 22%,color-mix(in srgb,var(--rm-card-accent) 20%,transparent),transparent 40%),linear-gradient(145deg,var(--rm-glass),var(--rm-glass-2))!important;box-shadow:var(--rm-inner),var(--rm-shadow-soft),0 0 22px color-mix(in srgb,var(--rm-card-accent) 16%,transparent)!important;border-color:color-mix(in srgb,var(--rm-card-accent) 32%,var(--rm-line))!important}
.med-action{--rm-card-accent:var(--record-med,var(--med))}.sleep-action{--rm-card-accent:var(--record-sleep,var(--sleep))}.buy-action{--rm-card-accent:var(--record-buy,var(--buy))}
.action-card:not(.primary-action){background:radial-gradient(circle at 50% 28%,color-mix(in srgb,var(--rm-card-accent,var(--accent)) 15%,transparent),transparent 44%),linear-gradient(145deg,var(--rm-glass),var(--rm-glass-2))!important;box-shadow:var(--rm-inner),var(--rm-shadow-soft),0 0 18px color-mix(in srgb,var(--rm-card-accent,var(--accent)) 12%,transparent)!important;border-color:color-mix(in srgb,var(--rm-card-accent,var(--accent)) 22%,var(--rm-line))!important}
.action-icon,.analysis-title>span,.notice-icon,.settings-row-icon{filter:drop-shadow(0 0 5px color-mix(in srgb,currentColor 42%,transparent));transition:transform .28s cubic-bezier(.2,.9,.2,1),filter .28s ease}
.action-card:active .action-icon,.settings-row:active .settings-row-icon{transform:scale(.92)}
.round-button,.sheet-close,.filter-chip,.secondary-button,.tiny-clear,.chart-review-btn{background:linear-gradient(145deg,var(--rm-glass),var(--rm-glass-2))!important;border:1px solid var(--rm-line)!important;box-shadow:var(--rm-inner),var(--rm-shadow-soft)!important}
.primary-button,.full-button,.filter-chip.selected{background:linear-gradient(145deg,color-mix(in srgb,var(--accent) 82%,white 18%),var(--accent))!important;color:#fff!important;border:1px solid color-mix(in srgb,var(--accent) 72%,white 28%)!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.32),0 0 16px color-mix(in srgb,var(--accent) 28%,transparent),0 10px 22px color-mix(in srgb,var(--accent) 16%,transparent)!important}
.metric,.analysis-row,.continuity-alert-row,.learning-context,.dose-result,.segmented,.emotion-advanced{background:linear-gradient(145deg,color-mix(in srgb,var(--surface-2) 82%,white 18%),var(--surface-2))!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.24),inset 0 0 18px color-mix(in srgb,var(--accent) 4%,transparent)}
.sheet{background:linear-gradient(155deg,color-mix(in srgb,var(--surface) 91%,white 9%),color-mix(in srgb,var(--surface) 96%,var(--accent) 4%))!important;border:1px solid var(--rm-line);box-shadow:inset 0 1px 0 rgba(255,255,255,.35),0 -18px 50px rgba(0,0,0,.20)!important;backdrop-filter:blur(22px) saturate(145%);-webkit-backdrop-filter:blur(22px) saturate(145%)}
.sheet-header{background:color-mix(in srgb,var(--surface) 86%,transparent)!important;backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px)}
.field input,.field textarea,.field select{background:linear-gradient(145deg,var(--rm-input),color-mix(in srgb,var(--rm-input) 92%,var(--accent) 8%))!important;border-color:color-mix(in srgb,var(--separator) 76%,white 24%)!important;box-shadow:inset 0 1px 2px rgba(0,0,0,.025),inset 0 0 16px color-mix(in srgb,var(--accent) 3%,transparent)}
.field input:focus,.field textarea:focus,.field select:focus{border-color:color-mix(in srgb,var(--accent) 72%,white 28%)!important;box-shadow:0 0 0 3px color-mix(in srgb,var(--accent) 13%,transparent),0 0 16px color-mix(in srgb,var(--accent) 16%,transparent),inset 0 1px 2px rgba(0,0,0,.02)!important}
.timeline-item:has(.kind-note){box-shadow:var(--rm-inner),var(--rm-shadow-soft),0 0 16px color-mix(in srgb,var(--record-note,var(--accent)) 8%,transparent)!important}.timeline-item:has(.kind-medication){box-shadow:var(--rm-inner),var(--rm-shadow-soft),0 0 16px color-mix(in srgb,var(--record-med,var(--med)) 8%,transparent)!important}.timeline-item:has(.kind-sleep){box-shadow:var(--rm-inner),var(--rm-shadow-soft),0 0 16px color-mix(in srgb,var(--record-sleep,var(--sleep)) 8%,transparent)!important}.timeline-item:has(.kind-purchase){box-shadow:var(--rm-inner),var(--rm-shadow-soft),0 0 16px color-mix(in srgb,var(--record-buy,var(--buy)) 8%,transparent)!important}
.segmented button.selected,.dimension-tabs button.selected{background:linear-gradient(145deg,color-mix(in srgb,var(--accent) 18%,var(--surface)),var(--surface))!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.35),0 0 13px color-mix(in srgb,var(--accent) 15%,transparent)!important}
.tab-bubble{box-shadow:inset 0 1px 0 rgba(255,255,255,.20),0 0 18px color-mix(in srgb,var(--accent) 18%,transparent)!important}.tab-item.selected>span{filter:drop-shadow(0 0 5px color-mix(in srgb,currentColor 40%,transparent))}
.dashboard-chart{overflow:hidden;position:relative}.dashboard-chart::before{content:"";position:absolute;inset:-80px auto auto -70px;width:190px;height:150px;border-radius:50%;background:radial-gradient(circle,color-mix(in srgb,var(--accent) 9%,transparent),transparent 70%);pointer-events:none}.local-chart-svg{overflow:visible}.chart-grid line{stroke:color-mix(in srgb,var(--secondary) 13%,transparent)!important}.chart-grid text,.chart-axis-label,.chart-bar-label,.chart-bar-value{fill:var(--secondary)!important}.rm-emotion-chart .chart-line{filter:drop-shadow(0 0 4px color-mix(in srgb,var(--accent) 14%,transparent))}
.rm-mood-block{padding:3px 0 2px}.mood-scale{grid-template-columns:repeat(6,minmax(0,1fr))!important;gap:10px!important}.mood-score{height:52px!important;border-radius:16px!important;border:1.5px solid var(--mood-border)!important;color:var(--mood-text)!important;background:linear-gradient(145deg,color-mix(in srgb,var(--mood-color) 78%,white 22%),var(--mood-color) 70%,color-mix(in srgb,var(--mood-color) 92%,white 8%))!important;box-shadow:inset 0 1px 1px rgba(255,255,255,.36),inset 0 0 12px color-mix(in srgb,var(--mood-color) 14%,transparent),0 0 10px var(--mood-glow)!important;font-size:16px;font-weight:850;transition:transform .28s cubic-bezier(.2,.9,.2,1),box-shadow .28s ease,filter .28s ease!important}.mood-score.rm-zero{background:radial-gradient(circle at 35% 22%,#393545 0%,#201E28 42%,#111116 100%)!important;box-shadow:inset 0 1px 2px rgba(190,170,255,.18),0 0 10px rgba(118,87,255,.42),0 0 20px rgba(118,87,255,.18)!important}.mood-score.selected{transform:scale(1.14) translateY(-2px)!important;z-index:4;border-width:2px!important;box-shadow:inset 0 1px 2px rgba(255,255,255,.58),0 0 0 2px color-mix(in srgb,var(--mood-border) 48%,white 52%),0 0 16px var(--mood-glow),0 0 31px var(--mood-glow)!important;animation:rmMoodBloom .34s cubic-bezier(.2,.95,.2,1)}.mood-score.rm-five.selected{box-shadow:inset 0 1px 3px rgba(255,255,255,.76),0 0 0 2px rgba(220,248,255,.90),0 0 18px rgba(86,200,255,.82),0 0 38px rgba(86,200,255,.48)!important;filter:saturate(1.06) brightness(1.04)}.mood-score:active{transform:scale(.94)!important}.mood-scale-labels{font-size:11px}.mood-scale-labels span:nth-child(2){text-align:center}.mood-scale-labels span:last-child{text-align:right}
.emotion-advanced{border:1px solid var(--rm-line);border-radius:20px;padding:12px 12px 14px;margin-top:14px}.emotion-advanced summary{font-weight:800;cursor:pointer}.emotion-dimension{margin-top:15px;padding:12px;border-radius:18px;background:radial-gradient(circle at 12% 0%,color-mix(in srgb,var(--dimension-color) 10%,transparent),transparent 42%),linear-gradient(145deg,var(--rm-glass),var(--rm-glass-2));border:1px solid color-mix(in srgb,var(--dimension-color) 16%,var(--rm-line));box-shadow:inset 0 1px 0 rgba(255,255,255,.35),0 0 18px color-mix(in srgb,var(--dimension-color) 7%,transparent)}.emotion-scale{grid-template-columns:repeat(5,minmax(0,1fr))!important;gap:8px!important}.emotion-scale button{--fill:8%;min-height:42px!important;border-radius:14px!important;border:1px solid color-mix(in srgb,var(--dimension-color) calc(var(--fill) + 18%),var(--separator))!important;background:color-mix(in srgb,var(--dimension-color) var(--fill),var(--surface-2))!important;color:var(--text)!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.20),0 0 8px color-mix(in srgb,var(--dimension-color) calc(var(--fill)/3),transparent);transition:transform .24s cubic-bezier(.2,.9,.2,1),box-shadow .24s ease,background .24s ease,border-color .24s ease}.emotion-scale button[data-emotion-score="0"]{--fill:7%}.emotion-scale button[data-emotion-score="1"]{--fill:18%}.emotion-scale button[data-emotion-score="2"]{--fill:34%}.emotion-scale button[data-emotion-score="3"]{--fill:56%;color:#fff!important;text-shadow:0 1px 6px rgba(0,0,0,.18)}.emotion-scale button[data-emotion-score="4"]{--fill:78%;color:#fff!important;text-shadow:0 1px 6px rgba(0,0,0,.20)}.emotion-scale button.selected{transform:scale(1.10) translateY(-1px);z-index:2;border:2px solid color-mix(in srgb,var(--dimension-color) 74%,white 26%)!important;background:color-mix(in srgb,var(--dimension-color) 88%,var(--surface))!important;color:#fff!important;box-shadow:inset 0 1px 2px rgba(255,255,255,.42),0 0 0 2px color-mix(in srgb,var(--dimension-color) 24%,transparent),0 0 15px color-mix(in srgb,var(--dimension-color) 48%,transparent),0 0 27px color-mix(in srgb,var(--dimension-color) 22%,transparent)!important}.emotion-scale-caption{font-size:10.5px!important}
@keyframes rmMoodBloom{0%{transform:scale(.96)}62%{transform:scale(1.18) translateY(-2px)}100%{transform:scale(1.14) translateY(-2px)}}
@keyframes rmCardIn{from{opacity:0;transform:translateY(7px)}to{opacity:1;transform:none}}
.view.active>.summary-card,.view.active>.analysis-card,.view.active>.notice-card,.view.active>.settings-group,.view.active>.action-section,.view.active>.recent-section{animation:rmCardIn .34s cubic-bezier(.2,.85,.2,1) both}
@media(prefers-color-scheme:dark){html[data-theme="system"]{--rm-glass:rgba(28,29,36,.72);--rm-glass-2:rgba(22,23,30,.66);--rm-line:rgba(255,255,255,.10);--rm-shadow:0 18px 42px rgba(0,0,0,.34);--rm-shadow-soft:0 9px 26px rgba(0,0,0,.26);--rm-inner:inset 0 1px 0 rgba(255,255,255,.08);--rm-input:rgba(42,43,52,.74)}html[data-theme="system"] body{background:radial-gradient(circle at 8% 4%,rgba(118,87,255,.15),transparent 28%),radial-gradient(circle at 92% 12%,rgba(35,168,255,.10),transparent 34%),radial-gradient(circle at 55% 86%,rgba(0,199,190,.07),transparent 36%),linear-gradient(180deg,#09090d,#000)!important}}
@media(prefers-reduced-motion:reduce){.mood-score,.emotion-scale button,.view.active>*{animation:none!important;transition:none!important}}
`;document.head.appendChild(st)})();

/* Inicialização: migra, renderiza e reaplica cores após conteúdo dinâmico. */
function rmApplyDimensionColors(root=document){root.querySelectorAll?.('[data-emotion-dimension]').forEach(row=>{const d=emotionDimensions().find(x=>x.id===row.dataset.emotionDimension);row.style.setProperty('--dimension-color',rmDimensionColor(d||{id:row.dataset.emotionDimension,label:row.dataset.emotionDimension}))})}
const rmObserver=new MutationObserver(()=>{rmApplyDimensionColors();rmFixAnalysisCopy()});rmObserver.observe(document.documentElement,{childList:true,subtree:true});
(async()=>{try{const changed=await rmMigrateScales();rmApplyDimensionColors();if(changed&&typeof renderAll==='function')await renderAll();else rmFixAnalysisCopy()}catch(err){console.error('Falha ao migrar escalas emocionais',err)}})();
